const body = document.getElementById('page-body');
const themeToggleBtn = document.getElementById('theme-toggle');
const themeIcon = document.getElementById('theme-icon');

// Initialize theme from localStorage if available
const savedTheme = localStorage.getItem('cv_theme');
if (savedTheme === 'dark') {
  body.classList.add('dark-theme');
  themeIcon.className = 'fa fa-moon-o';
} else {
  body.classList.remove('dark-theme');
  themeIcon.className = 'fa fa-sun-o';
}

// Toggle theme on button click
themeToggleBtn.addEventListener('click', () => {
  const isDark = body.classList.toggle('dark-theme');
  themeIcon.className = isDark ? 'fa fa-moon-o' : 'fa fa-sun-o';
  localStorage.setItem('cv_theme', isDark ? 'dark' : 'light');
});

/* ---------------------------
   Simple translation system
   --------------------------- */

const translations = {
  "en-US": {
    "meta.title": "Nivaldo Beirão - Online CV",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "IT Administrator and Manager",
    "location": "Miracatu - SP",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.Technology-&-Technical-Support": "Technology & Technical Support",
    "skills.Social-Projects-&-Digital-Inclusion": "Social Projects & Digital Inclusion",
    "skills.Academic-and-Administrative-Management": "Academic and Administrative Management",
    "skills.Sales-&-Commerce": "Sales & Commerce",
    "skills.Financial-&-Banking-Operations": "Financial and Banking Operations",
    "skills.Logistics-&-Operations": "Logistics & Operations",
    "skills.Sports-Trading-Investments": "Sports Trading (Investments)",
    
    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Continuous-learning-ability": "Continuous learning ability",
    "skills.Responsibilityand-commitment": "Responsibility and commitment",
    "skills.Organization-and-discipline": "Organization and discipline",
    "skills.Patience-and-resilience": "Patience and resilience",
    "skills.Initiative-and-proactivity": "Initiative and proactivity",
    "skills.Teamwork": "Teamwork",
    "skills.Adaptability-across-areas": "Adaptability across areas (commerce, technology, education, investments)",
    "skills.Analytical-skills": "Analytical skills (financial and sports analysis)",
    "skills.Emotional-and-psychological-control-under-pressure": "Emotional and psychological control under pressure",
    "skills.Interpersonal-communication": "Interpersonal communication",
    
    "languages.title": "Languages",
    "languages.pt": "Portuguese",
    "languages.en": "English",
    "languages.es": "Spanish",
    
    "about.title": "About",
    "about.text": "I am a perfectionist, detail-oriented, analytical, and process-driven professional. I focus on organization, clear documentation, and practical solutions that ensure operational stability and service continuity. I prioritize quality, rigorous review, and meeting deadlines, maintaining a discreet and reliable demeanor. I adopt a methodical approach to team and project management, seeking efficiency and continuous improvement. Sometimes shy, sometimes introverted, sometimes reserved; I am 35 years old, single, without children, and I dedicate part of my time to reading and continuous study to improve my technical and management knowledge. I am seeking an opportunity where my 17 years of experience can contribute to the company's development, applying discipline, attention to detail, and commitment to the delivery of IT and administrative services.",
    
    "experience.title": "Experiences",
    "experience.multimedia.title": "Multimedia Editor - Freelance work on Audacity",
    "experience.multimedia.date_text": "April 2023 -",
    "experience.multimedia.date_tag": "Present",
    "experience.multimedia.p1": "Creation and editing of multimedia digital content focused on quality, creativity, and AI innovation.",
    "experience.multimedia.p2": "Text: subtitling, translation, and adaptation for different audiences.",
    "experience.multimedia.p3": "Image: cover design, professional editing and pixel adjustments.",
    "experience.multimedia.p4": "Audio: conversion, cuts and adjustments, sound effects, reverb, normalization, and equalization.",
    "experience.multimedia.p5": "Video: dynamic editing, scene editing, audio adjustments, subtitles, and AI-assisted translations.",
    "experience.multimedia.p6": "Results: +7,500 audio files edited and saved in the cloud; +550 videos published with subtitles and translations in Portuguese, English, and Spanish.",
    
    "experience.sports-trader.title": "Sports Trader - Freelance work on Betfair",
    "experience.sports-trader.date_text": "March 2021 -",
    "experience.sports-trader.date_tag": "December 2021",
    "experience.sports-trader.p1": "Specialized services in sports investment operations, focusing on statistical analysis and intelligent strategies to maximize results.",
    "experience.sports-trader.p2": "Probability and Statistics applied to soccer games",
    "experience.sports-trader.p3": "Operations in the 1st half, 2nd half and entire game",
    "experience.sports-trader.p4": "Goal analysis (under/over), averages, percentages and decisive minutes",
    "experience.sports-trader.p5": "Back/Lay strategies for favorites, home and away teams",
    "experience.sports-trader.p6": "Pre-game, live and post-game analysis",
    "experience.sports-trader.p7": "Exclusive tools: investment diaries and calculator",
    "experience.sports-trader.p8": "Bankroll management and personalized trading plans",
    "experience.sports-trader.p9": "Emotional control and psychological discipline",
    "experience.sports-trader.p10": "Advanced study of odds (speed, interval and resistance)",
    "experience.sports-trader.p11": "Objective: to offer security, consistency and intelligence in decision-making for sports investors.",
    
    "experience.administrative-assistant.title": "Administrative Assistant - Vale Do Ribeira University Center (Univr)",
    "experience.administrative-assistant.date_text": "July 2016 -",
    "experience.administrative-assistant.date_tag": "September 2019",
    "experience.administrative-assistant.p1": "Sector: CTE (Educational Technology Center) Main activities:",
    "experience.administrative-assistant.p2": "Remote support,",
    "experience.administrative-assistant.p3": "Development, creation of layout and visual standardization,",
    "experience.administrative-assistant.p4": "Use of the main technological tools (Cloud - Drive, YouTube),",
    "experience.administrative-assistant.p5": "Management of the Virtual Learning Environment (AVA) - Moodle Platform. ",
    "experience.administrative-assistant.p6": "Elaboration of academic schedule (Urania),",
    "experience.administrative-assistant.p7": "Calendar of extra-class activities.",
    "experience.administrative-assistant.p8": "Receiving and sending e-mails,",
    "experience.administrative-assistant.p9": "Elaboration and control of various documents,",
    "experience.administrative-assistant.p10": "Control of internal information,",
    "experience.administrative-assistant.p11": "Elaboration of spreadsheets,",
    "experience.administrative-assistant.p12": "Elaboration of reports,",
    "experience.administrative-assistant.p13": "Assistance to faculty and students,",
    "experience.administrative-assistant.p14": "Direct assistance to the Institutional Researcher - responsible for completion of the Higher Education Census,",
    "experience.administrative-assistant.p15": "Assistance in registering and maintaining the ENADE,",
    "experience.administrative-assistant.p16": "Other day-to-day activities.",
    
    "experience.intern-registro.title": "Business Administration Intern - Regional Education Unit of Registro",
    "experience.intern-registro.date_text": "July 2014 -",
    "experience.intern-registro.date_tag": "June 2016",
    "experience.intern-registro.p1": "Sector: NIET (Nucleus of Educational Information and Technology)",
    "experience.intern-registro.p2": "Expertise in technical support level I, telephone, remote (TeamViewer) and field service.",
    "experience.intern-registro.p3": "Help Desk: Whats App Business, messenger, Blue Talk and other tools (Blue Control and Blue Lab)",
    "experience.intern-registro.p4": "Planning and development of social projects, digital inclusion, micro computing and social media.",
    "experience.intern-registro.p5": "Elaboration of activities related to the education, training and management of monitoring teams.",
    "experience.intern-registro.p6": "Computer maintenance and network configuration.",
    
    "experience.intern-miracatu.title": "Business Administration Intern - Regional Education Unit of Miracatu",
    "experience.intern-miracatu.date_text": "September 2011 -",
    "experience.intern-miracatu.date_tag": "August 2013",
    "experience.intern-miracatu.p1": "Sector: NIET (Nucleus of Educational Information and Technology)",
    "experience.intern-miracatu.p2": "Expertise in technical support level I, telephone, remote and field service.",
    "experience.intern-miracatu.p3": "Help Desk: messenger, Blue Talk and other tools (Blue Control and Blue Lab)",
    "experience.intern-miracatu.p4": "Planning and development of social projects, digital inclusion, micro computing and social media.",
    "experience.intern-miracatu.p5": "Elaboration of activities related to the education, training and management of monitoring teams.",
    "experience.intern-miracatu.p6": "Computer maintenance and network configuration,",
    "experience.intern-miracatu.p7": "HTML site update with Dreamweaver software.",
    
    "experience.cashier-bank.title": "Cashier - Bradesco Bank",
    "experience.cashier-bank.date_text": "April 2009 -",
    "experience.cashier-bank.date_tag": "March 2011",
    "experience.cashier-bank.p1": "Activities performed:",
    "experience.cashier-bank.p2": "Opening and closing of cash register, ensuring accuracy in financial records.",
    "experience.cashier-bank.p3": "Control and registration of income and expenses, ensuring organization and transparency.",
    "experience.cashier-bank.p4": "Sending mail and documents responsibly and punctually.",
    "experience.cashier-bank.p5": "Processing and receiving payments for bills (water, electricity, telephone, internet, and bank slips).",
    "experience.cashier-bank.p6": "Assisting retirees, pensioners, and INSS beneficiaries with withdrawals and payments.",
    "experience.cashier-bank.p7": "Managing payments to suppliers, maintaining a regular cash flow.",
    "experience.cashier-bank.p8": "Developed skills:",
    "experience.cashier-bank.p9": "Organization and attention to detail.",
    "experience.cashier-bank.p10": "Responsibility in handling cash.",
    "experience.cashier-bank.p11": "Customer service with empathy and efficiency.",
    "experience.cashier-bank.p12": "Agility in administrative and financial processes.",
    
    "experience.general-services.title": "General Services - Tio Beba Supermarkets",
    "experience.general-services.date_text": "January 2009 -",
    "experience.general-services.date_tag": "March 2011",
    "experience.general-services.p1": "Extensive professional experience in administrative, commercial, and operational areas, including:",
    "experience.general-services.p2": "Customer service and financial operations: working as a cashier in a supermarket and bank branch representing Bradesco; responsible for opening and closing the cash register, sending mailbags, processing payments, withdrawals, and assisting retirees and pensioners of the INSS (Brazilian National Social Security Institute); managing payments to suppliers.",
    "experience.general-services.p3": "Logistics and operations: organizing and restocking the sales area; packaging and checking merchandise; supporting home deliveries and loading; verifying receipt and unloading; dispatching deliveries.",
    "experience.general-services.p4": "Sales and commercial operations: experience as a salesperson of construction materials, agricultural products, and electronics; customer service; purchasing and pricing merchandise; inventory control and invoice verification.",
    "experience.general-services.p5": "Administration and support: file management, document organization, and support in administrative routines.",
    "experience.general-services.p6": "Skills developed:",
    "experience.general-services.p7": "Organization and attention to detail",
    "experience.general-services.p8": "Developed skills:",
    "experience.general-services.p9": "Responsibility in handling valuables",
    "experience.general-services.p10": "Interpersonal skills and customer service",
    "experience.general-services.p11": "Agility in logistics and administrative processes",
    "experience.general-services.p12": "Adaptability to different roles and departments",
    
    "education.title": "Education",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "October 2021 - Present",
    "education.dio.text": "Largest open IT education platform in Latin America, with over 1 million users. DIO partners with innovative companies, providing immersive learning experiences focused on employability. Main certifications are listed below.",
    "education.univr.mba": "VALE DO RIBEIRA UNIVERSITY CENTER (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.text": "MBA in Information Technology Management and Governance",
    "education.univr.bachelor": "VALE DO RIBEIRA UNIVERSITY CENTER (UNIVR) - Bachelor's",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.text": "Bachelor's Degree in Business Administration",
    
    "projects.title": "Projects",
    "projects.github": "GitHub",
    "projects.github.p1": "Creating a Canvas Type Application with Power Platform",
    "projects.github.p2": "Adding Security to APIs in AWS with Amazon Cognito",
    "projects.github.p3": "Exploring Rest Assured for API Test Automation",
    "projects.github.p4": "QA Professional: Manual Functional Testing",
    "projects.github.p5": "Implementing a Login Screen with Validation Using TypeScript",
    "projects.github.p6": "Developing the DIO Platform Registration Screen with React",
    "projects.github.p7": "Creating a GitHub Repository Wiki with React",
    "projects.github.p8": "Identifying Your Skills that Can be Monetized",
    "projects.github.p9": "AI Interviewer: Your Intelligent Interview Simulator",
    "projects.github.p10": "AI Career Mentor: Discover Your Future in Tech",
    "projects.github.p11": "Creating a Personal Finance Organization App with Vibe Coding",
    "projects.github.p12": "Creating a Calculator with React",
    "projects.github.p13": "Abstracting DIO Formations Using Object Orientation with Kotlin",
    "projects.github.p14": "Creating a BuzzFeed Clone with Angular",
    "projects.github.p15": "Creating a Blog with Angular",
    "projects.github.p16": "Building a Pokédex with JavaScript",
    "projects.github.p17": "Creating Your First Landing Page with HTML and CSS",
    "projects.github.p18": "Creating Your First Complete Website with HTML",
    "projects.github.p19": "Creating a Web Page Using Learned Tags",
    "projects.github.p20": "Creating a CI/CD Pipeline with Cloud Build and Terraform",
    "projects.github.p21": "Using Cloud Shell",
    "projects.github.p22": "Customizing Dashboard and Changing Language Preferences",
    "projects.github.p23": "Billing Export in Google Cloud Platform",
    "projects.github.p24": "Defining Billing Budget in Google Cloud Platform",
    "projects.github.p25": "Designing Your Folder and Project Organization and Access Groups in Google Cloud Platform",
    "projects.github.p26": "Creating a Deploy Pipeline with GitLab and Kubernetes",
    "projects.github.p27": "Creating an Application Deploy",
    "projects.github.p28": "Defining a Local Swarm Cluster with Vagrant",
    "projects.github.p29": "Creating a Container for a WEB Application",
    "projects.github.p30": "Exploring Demographics with Big Data Services in AWS",
    "projects.github.p31": "Training Neural Networks with Transfer Learning",
    "projects.github.p32": "Best Practices with DynamoDB",
    "projects.github.p33": "Creating Models with Python and Machine Learning to Predict COVID-19 Evolution in Brazil",
    "projects.github.p34": "Native App About Women's Football with Android Jetpack and Java",
    "projects.github.p35": "Creating the Front-end with ReactJS",
    "projects.github.p36": "Booking App DIO",
    "projects.github.p37": "Creating the iFood Interface with React Native",
    "projects.github.p38": "Infrastructure as Code with Serverless Framework on AWS",
    "projects.github.p39": "Creating a Star Wars Spacecraft Manager with SQL Server + .NET",
    "projects.github.p40": "Creating an Application for Currency Conversion and Exchange",
    "projects.github.p41": "Developing Your Blog with Java and Angular Technologies",
    "projects.github.p42": "Creating a ReactJS News Application Using PWA",
    "projects.github.p43": "Creating a Website to Find Restaurants Using Google Maps that Queries Google API",
    "projects.github.p44": "Creating Your Big Data Ecosystem in the Cloud",
    "projects.github.p45": "Data Analysis with Python and Pandas",
    "projects.github.p46": "Creating a Game Catalog Using Best Architecture Practices with .NET",
    "projects.github.p47": "Building a Project with Architecture Based on Microservices Using Spring Cloud",
    "projects.github.p48": "Building a Time and Access Control System with Spring Boot",
    "projects.github.p49": "Creating a Classifieds System with Ruby on Rails",
    "projects.github.p50": "MindApp - Developing Cloud Tags with Ruby",
    "projects.github.p51": "Create a Dragon Ball Z Sphere Manager Using ReactJS, Jest, React Testing Library and Cypress",
    "projects.github.p52": "Developing SPA with Angular",
    "projects.github.p53": "Creating a Budget System, Using CQRS, Quarkus, Kafka and Deploy on EKS",
    "projects.github.p54": "Running Your Java Application on Kubernetes. From Deploy to Debug without Fear!",
    "projects.github.p55": "Creating an E-commerce Solution with Microservices in Java",
    "projects.github.p56": "Creating Your Marvel and DC Super Heroes Manager in a Reactive API with Spring Boot",
    "projects.github.p57": "Using Cypress E2E to Test a Blog in Angular",
    "projects.github.p58": "Creating Project to Query Weather Forecast via API",
    "projects.github.p59": "Implementing Your Unit and Integration Testing Stack in a .NET Crowdfunding Project",
    "projects.github.p60": "Building a .NET API Project Integrated with MongoDB",
    "projects.github.p61": "Building a ChatbotFit on Telegram with JavaScript and NodeJS",
    "projects.github.p62": "Building Sexy APIs Using Serverless Architecture",
    "projects.github.p63": "Background Tasks Using Node.js and Redis",
    "projects.github.p64": "Requesting Data from a Cryptocurrency API",
    "projects.github.p65": "Practical Introduction to TypeScript",
    "projects.github.p66": "Learning Spring Data JPA in Practice with Java",
    "projects.github.p67": "Tech Potential Challenge: Payment API",
    "projects.github.p68": "Building a Task Scheduling System with Entity Framework",
    "projects.github.p69": "Creating a System and Abstracting a Smartphone with OOP in C#",
    "projects.github.p70": "Building a Hotel Hosting System in C#",
    "projects.github.p71": "Building a Parking System with C#",
    "projects.github.p72": "The Role of SQL and NoSQL Databases in Data Engineering",
    "projects.github.p73": "Build a Logical Database Project from Scratch",
    "projects.github.p74": "Building Your First Logical Database Project",
    "projects.github.p75": "Building a Conceptual Database Schema",
    "projects.github.p76": "Refining a Conceptual Database Design – E-COMMERCE",
    "projects.github.p77": ".Docker: Practical Use in the Microservices Scenario",
    "projects.github.p78": "Infrastructure as Code - Web Server Provisioning Script (Apache)",
    "projects.github.p79": "Infrastructure as Code: Script for Creating User, Directory Structure and Permissions",
    "projects.github.p80": "Performing Cloud Deploy of a Set of APIs Developed in Spring Boot",
    "projects.github.p81": "Integrating a Node.js Backend with a React Frontend for an E-commerce",
    "projects.github.p82": "Developing a Hamburger Menu and Morphing Menu with CSS Transitions",
    "projects.github.p83": "Building an App Using Motion Sensor with React Native",
    "projects.github.p84": "Learn to Create a Parking System Using TypeScript",
    "projects.github.p85": "How to Create a Front-end for an E-commerce Using Angular",
    "projects.github.p86": "Developing a Progressive Web Application with React to Map COVID-19 Data Around the World",
    "projects.github.p87": "Development of Unit Tests to Validate a REST API for Beer Inventory Management",
    "projects.github.p88": "Create Your Meeting Room Manager with Java and Angular",
    "projects.github.p89": "Building a REST API for Querying Brazilian Cities from Zero to Production",
    "projects.github.p90": "Developing a People Management System in REST API with Spring Boot",
    "projects.github.p91": "Creating Your Game in Space Shooter Style",
    "projects.github.p92": "Creating Your Own Tic-Tac-Toe Game with HTML and Javascript",
    "projects.github.p93": "Developing a Memory Game",
    "projects.github.p94": "Building Your First Spaceship Game",
    "projects.github.p95": "Recreating the Famous Dinosaur Game without Internet",
    "projects.github.p96": "Creating a Fully Managed Hadoop Ecosystem with Google Cloud Dataproc",
    "projects.github.p97": "MySql - How to Model a Watched Series Control Database",
    "projects.github.p98": "Simplifying the Creation of Image Processing Packages in Python",
    "projects.github.p99": "Building a URL Shortener",
    "projects.github.p100": "Creating a Fully Componentized Front-end in Practice with ReactJS",
    "projects.github.p101": "Creating Your Memory Game Genius Style",
    "projects.github.p102": "Creating an App to Showcase Your GitHub Portfolio",
    "projects.github.p103": "Creating a Business Card App in Kotlin",
    "projects.github.p104": "Creating a Reminders and Tasks App with Kotlin",
    "projects.github.p105": "Exploring Design Patterns in Practice with Java",
    "projects.github.p106": "Abstracting a Bootcamp Using Object Orientation in Java",
    "projects.github.p107": "Creating a Digital Bank with Java and Object Orientation",
    "projects.github.p108": "Abstracting an RPG Game Using Object Orientation with C#",
    "projects.github.p109": "Recreating the Snake Game with JavaScript",
    "projects.github.p110": "Recreating the Netflix Interface",
    "projects.github.p111": "Recreating Instagram's Homepage",
    "projects.github.p112": "Creating Your First GitHub Repository to Share Your Progress",
    "projects.github.p113": "Creating a Simple Series Registration App in .NET",
    "projects.github.p114": "Creating a Bank Transfer Application with .NET",
    "projects.github.p115": "Creating Your Online CV With HTML and GitHub Pages",
    "projects.github.p116": "Creating Robust Solutions in Dynamics 365 with the SDK Extension",
    "projects.github.p117": "Documenting and Testing Your REST API with Kotlin",
    "projects.github.p118": "Contributing to an Open Source Project on GitHub",
    "projects.github.p119": "Simulating a Bank Account Through the Terminal/Console",
    "projects.github.p120": "Creating a Small System for Validation of a Selection Process",
    "projects.github.p121": "Modeling the iPhone with UML: Music, Calls and Internet Functions",
    
    "footer.social": "My Social Networks",
    "footer.powered": "Powered by w3.css"
  },

  "pt-BR": {
    "meta.title": "Nivaldo Beirão - CV Online",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "Administrador e Gerente de TI",
    "location": "Miracatu - SP",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.Technology-&-Technical-Support": "Tecnologia e Suporte Técnico",
    "skills.Social-Projects-&-Digital-Inclusion": "Projetos Sociais e Inclusão Digital",
    "skills.Academic-and-Administrative-Management": "Gestão Acadêmica e Administrativa",
    "skills.Sales-&-Commerce": "Vendas e Comércio",
    "skills.Financial-&-Banking-Operations": "Operações Financeiras e Bancárias",
    "skills.Logistics-&-Operations": "Logística e Operações",
    "skills.Sports-Trading-Investments": "Sports Trading (Investimentos)",
    
    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Continuous-learning-ability": "Capacidade de aprendizagem contínua",
    "skills.Responsibilityand-commitment": "Responsabilidade e comprometimento",
    "skills.Organization-and-discipline": "Organização e disciplina",
    "skills.Patience-and-resilience": "Paciência e resiliência",
    "skills.Initiative-and-proactivity": "Iniciativa e proatividade",
    "skills.Teamwork": "Trabalho em equipe",
    "skills.Adaptability-across-areas": "Adaptabilidade entre áreas (comércio, tecnologia, educação, investimentos)",
    "skills.Analytical-skills": "Habilidades analíticas (análise financeira e esportiva)",
    "skills.Emotional-and-psychological-control-under-pressure": "Controle emocional e psicológico sob pressão",
    "skills.Interpersonal-communication": "Comunicação interpessoal",
    
    "languages.title": "Idiomas",
    "languages.pt": "Português",
    "languages.en": "Inglês",
    "languages.es": "Espanhol",
    
    "about.title": "Sobre",
    "about.text": "Sou perfeccionista, orientado a detalhes, analítico e com foco em processos. Priorizo organização, documentação clara e soluções práticas que garantam estabilidade operacional e continuidade de serviço. Valorizo qualidade, revisão rigorosa e cumprimento de prazos, mantendo postura discreta e confiável. Adoto abordagem metódica na gestão de equipes e projetos, buscando eficiência e melhoria contínua. Às vezes tímido, às vezes introvertido, às vezes reservado; tenho 35 anos, solteiro, sem filhos, e dedico parte do meu tempo à leitura e estudo contínuo para aprimorar conhecimentos técnicos e de gestão. Busco uma oportunidade onde meus 17 anos de experiência possam contribuir para o desenvolvimento da empresa, aplicando disciplina, atenção aos detalhes e compromisso com a entrega de serviços de TI e administrativos.",
    
    "experience.title": "Experiências",
    "experience.multimedia.title": "Editor Multimídia - Trabalho Freelance com Audacity",
    "experience.multimedia.date_text": "Abril 2023 -",
    "experience.multimedia.date_tag": "Presente",
    "experience.multimedia.p1": "Criação e edição de conteúdo multimídia digital com foco em qualidade, criatividade e inovação em IA.",
    "experience.multimedia.p2": "Texto: legendagem, tradução e adaptação para diferentes públicos.",
    "experience.multimedia.p3": "Imagem: design de capa, edição profissional e ajustes de pixels.",
    "experience.multimedia.p4": "Áudio: conversão, cortes e ajustes, efeitos sonoros, reverb, normalização e equalização.",
    "experience.multimedia.p5": "Vídeo: edição dinâmica, edição de cenas, ajustes de áudio, legendas e traduções assistidas por IA.",
    "experience.multimedia.p6": "Resultados: +7.500 arquivos de áudio editados e salvos na nuvem; +550 vídeos publicados com legendas e traduções em Português, Inglês e Espanhol.",
    
    "experience.sports-trader.title": "Trader Esportivo - Trabalho Freelance na Betfair",
    "experience.sports-trader.date_text": "Março 2021 -",
    "experience.sports-trader.date_tag": "Dezembro 2021",
    "experience.sports-trader.p1": "Serviços especializados em operações de investimento esportivo, com foco em análise estatística e estratégias inteligentes para maximizar resultados.",
    "experience.sports-trader.p2": "Probabilidade e Estatística aplicadas ao futebol",
    "experience.sports-trader.p3": "Operações no 1º tempo, 2º tempo e jogo inteiro",
    "experience.sports-trader.p4": "Análise de gols (under/over), médias, percentuais e minutos decisivos",
    "experience.sports-trader.p5": "Estratégias Back/Lay para favoritos, mandante e visitante",
    "experience.sports-trader.p6": "Análise pré-jogo, ao vivo e pós-jogo",
    "experience.sports-trader.p7": "Ferramentas exclusivas: diários de investimento e calculadora",
    "experience.sports-trader.p8": "Gerenciamento de Bankroll e planos de trading personalizados",
    "experience.sports-trader.p9": "Controle emocional e disciplina psicológica",
    "experience.sports-trader.p10": "Estudo avançado de odds (velocidade, intervalo e resistência)",
    "experience.sports-trader.p11": "Objetivo: oferecer segurança, consistência e inteligência na tomada de decisão para investidores esportivos.",
    
    "experience.administrative-assistant.title": "Assistente Administrativo - Centro Universitário Vale Do Ribeira (Univr)",
    "experience.administrative-assistant.date_text": "Julho 2016 -",
    "experience.administrative-assistant.date_tag": "Setembro 2019",
    "experience.administrative-assistant.p1": "Setor: CTE (Centro de Tecnologia Educacional) Principais atividades:",
    "experience.administrative-assistant.p2": "Suporte remoto,",
    "experience.administrative-assistant.p3": "Desenvolvimento, criação de layout e padronização visual,",
    "experience.administrative-assistant.p4": "Uso das principais ferramentas tecnológicas (Nuvem - Drive, YouTube),",
    "experience.administrative-assistant.p5": "Gerenciamento do Ambiente Virtual de Aprendizagem (AVA) - Plataforma Moodle.",
    "experience.administrative-assistant.p6": "Elaboração de cronograma acadêmico (Urania),",
    "experience.administrative-assistant.p7": "Calendário de atividades extraclasse.",
    "experience.administrative-assistant.p8": "Recebimento e envio de e-mails,",
    "experience.administrative-assistant.p9": "Elaboração e controle de diversos documentos,",
    "experience.administrative-assistant.p10": "Controle de informações internas,",
    "experience.administrative-assistant.p11": "Elaboração de planilhas,",
    "experience.administrative-assistant.p12": "Elaboração de relatórios,",
    "experience.administrative-assistant.p13": "Atendimento a docentes e estudantes,",
    "experience.administrative-assistant.p14": "Atendimento direto ao Pesquisador Institucional - responsável pelo preenchimento do Censo de Educação Superior,",
    "experience.administrative-assistant.p15": "Auxílio no registro e manutenção do ENADE,",
    "experience.administrative-assistant.p16": "Demais atividades do dia a dia.",
    
    "experience.intern-registro.title": "Estagiário em Administração - Unidade Regional de Educação de Registro",
    "experience.intern-registro.date_text": "Julho 2014 -",
    "experience.intern-registro.date_tag": "Junho 2016",
    "experience.intern-registro.p1": "Setor: NIET (Núcleo de Informação e Tecnologia Educacional)",
    "experience.intern-registro.p2": "Expertise em suporte técnico nível I, telefônico, remoto (TeamViewer) e atendimento presencial.",
    "experience.intern-registro.p3": "Help Desk: WhatsApp Empresarial, Messenger, Blue Talk e outras ferramentas (Blue Control e Blue Lab)",
    "experience.intern-registro.p4": "Planejamento e desenvolvimento de projetos sociais, inclusão digital, microinformática e mídias sociais.",
    "experience.intern-registro.p5": "Elaboração de atividades relacionadas à educação, treinamento e gestão de equipes de monitoramento.",
    "experience.intern-registro.p6": "Manutenção de computadores e configuração de redes.",
    
    "experience.intern-miracatu.title": "Estagiário em Administração - Unidade Regional de Educação de Miracatu",
    "experience.intern-miracatu.date_text": "Setembro 2011 -",
    "experience.intern-miracatu.date_tag": "Agosto 2013",
    "experience.intern-miracatu.p1": "Setor: NIET (Núcleo de Informação e Tecnologia Educacional)",
    "experience.intern-miracatu.p2": "Expertise em suporte técnico nível I, telefônico, remoto e atendimento presencial.",
    "experience.intern-miracatu.p3": "Help Desk: Messenger, Blue Talk e outras ferramentas (Blue Control e Blue Lab)",
    "experience.intern-miracatu.p4": "Planejamento e desenvolvimento de projetos sociais, inclusão digital, microinformática e mídias sociais.",
    "experience.intern-miracatu.p5": "Elaboração de atividades relacionadas à educação, treinamento e gestão de equipes de monitoramento.",
    "experience.intern-miracatu.p6": "Manutenção de computadores e configuração de redes,",
    "experience.intern-miracatu.p7": "Atualização de site HTML com software Dreamweaver.",
    
    "experience.cashier-bank.title": "Caixa - Banco Bradesco",
    "experience.cashier-bank.date_text": "Abril 2009 -",
    "experience.cashier-bank.date_tag": "Março 2011",
    "experience.cashier-bank.p1": "Atividades realizadas:",
    "experience.cashier-bank.p2": "Abertura e fechamento de caixa, garantindo precisão nos registros financeiros.",
    "experience.cashier-bank.p3": "Controle e registro de receitas e despesas, garantindo organização e transparência.",
    "experience.cashier-bank.p4": "Envio de malotes e documentos de forma responsável e pontual.",
    "experience.cashier-bank.p5": "Processamento e recebimento de pagamentos de contas (água, luz, telefone, internet e boletos).",
    "experience.cashier-bank.p6": "Atendimento a aposentados, pensionistas e beneficiários do INSS com saques e pagamentos.",
    "experience.cashier-bank.p7": "Gerenciamento de pagamentos a fornecedores, mantendo fluxo de caixa regular.",
    "experience.cashier-bank.p8": "Competências desenvolvidas:",
    "experience.cashier-bank.p9": "Organização e atenção aos detalhes.",
    "experience.cashier-bank.p10": "Responsabilidade na manipulação de valores.",
    "experience.cashier-bank.p11": "Atendimento ao cliente com empatia e eficiência.",
    "experience.cashier-bank.p12": "Agilidade em processos administrativos e financeiros.",
    
    "experience.general-services.title": "Serviços Gerais - Supermercados Tio Beba",
    "experience.general-services.date_text": "Janeiro 2009 -",
    "experience.general-services.date_tag": "Março 2011",
    "experience.general-services.p1": "Experiência profissional extensa em áreas administrativas, comerciais e operacionais, incluindo:",
    "experience.general-services.p2": "Atendimento ao cliente e operações financeiras: atuação como caixa em supermercado e agência bancária representando o Bradesco; responsável pela abertura e fechamento de caixa, envio de malotes, processamento de pagamentos, saques e assistência a aposentados e pensionistas do INSS (Instituto Nacional de Seguro Social Brasileiro); gerenciamento de pagamentos a fornecedores.",
    "experience.general-services.p3": "Logística e operações: organização e reposição da área de vendas; embalagem e verificação de mercadorias; apoio em entregas domiciliares e carregamento; verificação de recebimento e descarregamento; despacho de entregas.",
    "experience.general-services.p4": "Vendas e operações comerciais: experiência como vendedor de materiais de construção, produtos agrícolas e eletrônicos; atendimento ao cliente; compra e precificação de mercadorias; controle de inventário e verificação de faturas.",
    "experience.general-services.p5": "Administração e apoio: gerenciamento de arquivos, organização de documentos e apoio em rotinas administrativas.",
    "experience.general-services.p6": "Competências desenvolvidas:",
    "experience.general-services.p7": "Organização e atenção aos detalhes",
    "experience.general-services.p8": "Competências desenvolvidas:",
    "experience.general-services.p9": "Responsabilidade na manipulação de valores",
    "experience.general-services.p10": "Habilidades interpessoais e atendimento ao cliente",
    "experience.general-services.p11": "Agilidade em processos logísticos e administrativos",
    "experience.general-services.p12": "Adaptabilidade para diferentes funções e departamentos",
    
    "education.title": "Educação",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "Outubro 2021 - Presente",
    "education.dio.text": "Maior plataforma de educação aberta em TI da América Latina, com mais de 1 milhão de usuários. A DIO faz parcerias com empresas inovadoras, oferecendo experiências de aprendizagem imersivas com foco em empregabilidade. Principais certificações listadas abaixo.",
    "education.univr.mba": "CENTRO UNIVERSITÁRIO VALE DO RIBEIRA (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.text": "MBA em Gestão e Governança de Tecnologia da Informação",
    "education.univr.bachelor": "CENTRO UNIVERSITÁRIO VALE DO RIBEIRA (UNIVR) - Bacharelado",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.text": "Bacharel em Administração de Empresas",
    
    "projects.title": "Projetos",
    "projects.github": "GitHub",
    "projects.github.p1": "Criando um aplicativo do tipo Canvas com a Power Platform",
    "projects.github.p2": "Adicionando Segurança em APIs na AWS com Amazon Cognito",
    "projects.github.p3": "Explorando o Rest Assured Para a Automação de Testes de API",
    "projects.github.p4": "O Dia a Dia de um QA: A Prática de Testes Manuais Funcionais",
    "projects.github.p5": "Implementando Uma Tela de Login Com Validação Usando TypeScript",
    "projects.github.p6": "Desenvolvendo a Tela de Cadastro da Plataforma Dio com React",
    "projects.github.p7": "Criando Uma Wiki de Repositórios do GitHub Com React",
    "projects.github.p8": "Identificando suas Habilidades que Podem ser Remuneradas",
    "projects.github.p9": "IA Entrevistador: Seu Simulador Inteligente de Entrevistas",
    "projects.github.p10": "IA Mentor de Carreira: Descubra Seu Futuro em Tech",
    "projects.github.p11": "Criando um APP de Organização de Finanças Pessoais com Vibe Coding",
    "projects.github.p12": "Criando Uma Calculadora Com React",
    "projects.github.p13": "Abstraindo Formações da DIO Usando Orientação a Objetos com Kotlin",
    "projects.github.p14": "Criando um Clone do BuzzFeed com Angular",
    "projects.github.p15": "Criando um Blog com Angular",
    "projects.github.p16": "Construindo uma Pokédex com JavaScript",
    "projects.github.p17": "Criando sua Primeira Landing Page com HTML e CSS",
    "projects.github.p18": "Criando seu Primeiro Site Completo com HTML",
    "projects.github.p19": "Criar Uma Página Web Utilizando as Tags Aprendidas",
    "projects.github.p20": "Criando Pipeline de CI/CD com Cloud Build e Terraform",
    "projects.github.p21": "Utilizando o Cloud Shell",
    "projects.github.p22": "Personalizando Dashboard e Trocando as Preferências de Idioma",
    "projects.github.p23": "Exportação do Billing na Google Cloud Platform",
    "projects.github.p24": "Definição de Orçamento de Billing na Google Cloud Platform",
    "projects.github.p25": "Desenhando Sua Organização de Pastas e Projetos e Grupos de Acessos na Google Cloud Platform",
    "projects.github.p26": "Criando um Pipeline de Deploy com GitLab e Kubernetes",
    "projects.github.p27": "Criando um Deploy de uma Aplicação",
    "projects.github.p28": "Definição de um Cluster Swarm Local com o Vagrant",
    "projects.github.p29": "Criando um Container de uma Aplicação WEB",
    "projects.github.p30": "Explorando Dados Demográficos com Serviços de Big Data na AWS",
    "projects.github.p31": "Treinamento de Redes Neurais com Transfer Learning",
    "projects.github.p32": "Boas práticas com DynamoDB",
    "projects.github.p33": "Criando Modelos com Python e Machine Learning para Prever a Evolução do COVID-19 no Brasil",
    "projects.github.p34": "App Nativo Sobre Futebol Feminino com Android Jetpack e Java",
    "projects.github.p35": "Criando o Front-end com ReactJS",
    "projects.github.p36": "Booking App DIO",
    "projects.github.p37": "Criando a Interface do iFood com React Native",
    "projects.github.p38": "Infraestrutura Como Código com Serverless Framework na AWS",
    "projects.github.p39": "Criando um Gerenciador de Espaçonaves do Star Wars com SQL Server + .NET",
    "projects.github.p40": "Criando um Aplicativo para Conversão de Moedas e Câmbio",
    "projects.github.p41": "Desenvolvendo seu Blog com as Tecnologias de Java e Angular",
    "projects.github.p42": "Criando uma Aplicação ReactJS de Notícias Utilizando PWA",
    "projects.github.p43": "Criando um Site para Encontrar Restaurantes Usando Google Maps que Consulta API do Google",
    "projects.github.p44": "Criando seu Ecossistema de Big Data na Nuvem",
    "projects.github.p45": "Análise de dados com Python e Pandas",
    "projects.github.p46": "Criando um Catálogo de Jogos Usando Boas Práticas de Arquitetura com .NET",
    "projects.github.p47": "Construindo um Projeto com Arquitetura Baseada em Microsserviços Usando Spring Cloud",
    "projects.github.p48": "Construindo um Sistema de Controle de Ponto e Acesso com Spring Boot",
    "projects.github.p49": "Criando um Sistema de Classificados com Ruby on Rails",
    "projects.github.p50": "MindApp - Desenvolvendo uma Cloud Tags com Ruby",
    "projects.github.p51": "Crie um Gerenciador de Esferas do Dragon Ball Z Usando ReactJS, Jest, React Testing Library e Cypress",
    "projects.github.p52": "Desenvolvendo SPA com Angular",
    "projects.github.p53": "Criando um Sistema de Orçamento, Utilizando CQRS, Quarkus, Kafka e Deploy no EKS",
    "projects.github.p54": "Rodando sua Aplicação Java no Kubernetes. Do Deploy ao Debug sem Medo!",
    "projects.github.p55": "Criando uma Solução de E-commerce com Microsserviços em Java",
    "projects.github.p56": "Criando seu Gerenciador de Super Heróis da Marvel e da DC em uma API Reativa com Spring Boot",
    "projects.github.p57": "Utilizando o Cypress E2E para testar um Blog em Angular",
    "projects.github.p58": "Criando Projeto para Consultar a Previsão do Tempo via API",
    "projects.github.p59": "Implementando sua Stack de Testes de Unidade e Integrados em um Projeto .NET de Crowdfunding",
    "projects.github.p60": "Construindo um Projeto de uma API.NET Integrada ao MongoDB",
    "projects.github.p61": "Construindo um ChatbotFit no Telegram com JavaScript e NodeJS",
    "projects.github.p62": "Construindo sexy APIs Usando Arquitetura Serverless",
    "projects.github.p63": "Tarefas em Background Utilizando Node.js e Redis",
    "projects.github.p64": "Requisitando Dados de uma API de Criptomoedas",
    "projects.github.p65": "Introdução Prática ao TypeScript",
    "projects.github.p66": "Conhecendo Spring Data JPA na prática com Java",
    "projects.github.p67": "Desafio Tech Pottencial: Payment API",
    "projects.github.p68": "Construindo um Sistema de Agendamento de Tarefas com Entity Framework",
    "projects.github.p69": "Criando um Sistema e Abstraindo um Celular com POO em C#",
    "projects.github.p70": "Construindo um Sistema de Hospedagem de um Hotel no C#",
    "projects.github.p71": "Construindo um Sistema para um Estacionamento com C#",
    "projects.github.p72": "O Papel dos Bancos de Dados SQL e NoSQL na Engenharia de Dados",
    "projects.github.p73": "Construa um Projeto Lógico de Banco de Dados do Zero",
    "projects.github.p74": "Construindo seu Primeiro Projeto Lógico de Banco de Dados",
    "projects.github.p75": "Construindo um Esquema Conceitual para Banco De dados",
    "projects.github.p76": "Refinando um Projeto Conceitual de Banco de Dados – E-COMMERCE",
    "projects.github.p77": ".Docker: Utilização Prática no Cenário de Microsserviços",
    "projects.github.p78": "Infraestrutura como Código - Script de Provisionamento de um Servidor Web (Apache)",
    "projects.github.p79": "Infraestrutura como Código: Script de Criação de Estrutura de Usuários, Diretórios e Permissões",
    "projects.github.p80": "Realizando Deploy na Nuvem de um Conjunto de API's Desenvolvida em Spring Boot",
    "projects.github.p81": "Integrando um Backend em Node.js com um Frontend em React para um E-commerce",
    "projects.github.p82": "Desenvolvendo um Menu Hamburguer e Morphing Menu com CSS Transitions",
    "projects.github.p83": "Construindo um App usando Sensor de Movimento com React Native",
    "projects.github.p84": "Aprenda a Criar um Sistema de Estacionamento Usando TypeScript",
    "projects.github.p85": "Como criar um front-end de um e-commerce utilizando Angular",
    "projects.github.p86": "Desenvolvendo uma Progressive Web Application com React para Mapear os Dados do COVID19 Pelo Mundo",
    "projects.github.p87": "Desenvolvimento de Testes Unitários para Validar uma API REST de Gerenciamento Estoques de Cerveja",
    "projects.github.p88": "Crie seu Gerenciador de Salas de Reuniões com Java e Angular",
    "projects.github.p89": "Construindo uma API Rest de Consulta de Cidades do Brasil do Zero até a Produção",
    "projects.github.p90": "Desenvolvendo um Sistema de Gerenciamento de Pessoas em API REST com Spring Boot",
    "projects.github.p91": "Criando seu Jogo no Estilo Space Shooter",
    "projects.github.p92": "Criando seu Próprio Jogo da Velha com HTML e Javascript",
    "projects.github.p93": "Desenvolvendo um Jogo da Memória",
    "projects.github.p94": "Construindo o seu Primeiro Jogo de Naves",
    "projects.github.p95": "Recriando o Famoso Jogo do Dinossauro sem Internet",
    "projects.github.p96": "Criando um Ecossistema Hadoop Totalmente Gerenciado com Google Cloud Dataproc",
    "projects.github.p97": "MySql - Como Modelar um Banco de Controle de Séries Assistidas",
    "projects.github.p98": "Descomplicando a Criação de Pacotes de Processamento de Imagens em Python",
    "projects.github.p99": "Construindo Encurtador de URL",
    "projects.github.p100": "Criando um Front-end Totalmente Componentizado na Prática com ReactJS",
    "projects.github.p101": "Criando seu Jogo de Memória Estilo Genius",
    "projects.github.p102": "Criando um App para Apresentar seu Portfólio do GitHub",
    "projects.github.p103": "Criando um App de Cartão de Visitas em Kotlin",
    "projects.github.p104": "Criando um App de Lembretes e Tarefas com Kotlin",
    "projects.github.p105": "Explorando Padrões de Projetos na Prática com Java",
    "projects.github.p106": "Abstraindo um Bootcamp Usando Orientação a Objetos em Java",
    "projects.github.p107": "Criando um Banco Digital com Java e Orientação a Objetos",
    "projects.github.p108": "Abstraindo um Jogo de RPG Usando Orientação a Objetos com C#",
    "projects.github.p109": "Recriando o Jogo da Cobrinha com JavaScript",
    "projects.github.p110": "Recriando a Interface do Netflix",
    "projects.github.p111": "Recriando a Página Inicial do Instagram",
    "projects.github.p112": "Criando seu Primeiro Repositório no GitHub Para Compartilhar Seu Progresso",
    "projects.github.p113": "Criando um APP Simples de Cadastro de Séries em .NET",
    "projects.github.p114": "Criando uma Aplicação de Transferências Bancárias com .NET",
    "projects.github.p115": "Criando seu CV Online com HTML e GitHub Pages",
    "projects.github.p116": "Criando Soluções Robusta em Dynamics 365 com a Extensão do SDK",
    "projects.github.p117": "Documentando e Testando sua API Rest com Kotlin",
    "projects.github.p118": "Contribuindo para um Projeto Open Source no GitHub",
    "projects.github.p119": "Simulando uma Conta Bancária Através do Terminal/Console",
    "projects.github.p120": "Criando um Pequeno Sistema para Validação de um Processo Seletivo",
    "projects.github.p121": "Modelando o iPhone com UML: Funções de Música, Ligações e Internet",
    
    "footer.social": "Minhas Redes Sociais",
    "footer.powered": "Desenvolvido com w3.css"
  },

  "es-ES": {
    "meta.title": "Nivaldo Beirão - CV Online",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "Administrador y Gerente de TI",
    "location": "Miracatu - SP",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.Technology-&-Technical-Support": "Tecnología y Soporte Técnico",
    "skills.Social-Projects-&-Digital-Inclusion": "Proyectos Sociales e Inclusión Digital",
    "skills.Academic-and-Administrative-Management": "Gestión Académica y Administrativa",
    "skills.Sales-&-Commerce": "Ventas y Comercio",
    "skills.Financial-&-Banking-Operations": "Operaciones Financieras y Bancarias",
    "skills.Logistics-&-Operations": "Logística y Operaciones",
    "skills.Sports-Trading-Investments": "Sports Trading (Inversiones)",
    
    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Continuous-learning-ability": "Capacidad de aprendizaje continuo",
    "skills.Responsibilityand-commitment": "Responsabilidad y compromiso",
    "skills.Organization-and-discipline": "Organización y disciplina",
    "skills.Patience-and-resilience": "Paciencia y resiliencia",
    "skills.Initiative-and-proactivity": "Iniciativa y proactividad",
    "skills.Teamwork": "Trabajo en equipo",
    "skills.Adaptability-across-areas": "Adaptabilidad entre áreas (comercio, tecnología, educación, inversiones)",
    "skills.Analytical-skills": "Habilidades analíticas (análisis financiero y deportivo)",
    "skills.Emotional-and-psychological-control-under-pressure": "Control emocional y psicológico bajo presión",
    "skills.Interpersonal-communication": "Comunicación interpersonal",
    
    "languages.title": "Idiomas",
    "languages.pt": "Portugués",
    "languages.en": "Inglés",
    "languages.es": "Español",
    
    "about.title": "Acerca de",
    "about.text": "Soy perfeccionista, orientado a los detalles, analítico y con enfoque en procesos. Me centro en la organización, documentación clara y soluciones prácticas que aseguren la estabilidad operativa y la continuidad del servicio. Priorizo la calidad, la revisión rigurosa y el cumplimiento de plazos, manteniendo una actitud discreta y confiable. Adopto un enfoque metódico en la gestión de equipos y proyectos, buscando eficiencia y mejora continua. A veces tímido, a veces introvertido, a veces reservado; tengo 35 años, soltero, sin hijos, y dedico parte de mi tiempo a la lectura y al estudio continuo para mejorar mis conocimientos técnicos y de gestión. Busco una oportunidad donde mis 17 años de experiencia puedan contribuir al desarrollo de la empresa, aplicando disciplina, atención al detalle y compromiso con la entrega de servicios de TI y administrativos.",
    
    "experience.title": "Experiencias",
    "experience.multimedia.title": "Editor Multimedia - Trabajo Freelance con Audacity",
    "experience.multimedia.date_text": "Abril 2023 -",
    "experience.multimedia.date_tag": "Presente",
    "experience.multimedia.p1": "Creación y edición de contenido multimedia digital enfocado en calidad, creatividad e innovación en IA.",
    "experience.multimedia.p2": "Texto: subtitulado, traducción y adaptación para diferentes audiencias.",
    "experience.multimedia.p3": "Imagen: diseño de portada, edición profesional y ajustes de píxeles.",
    "experience.multimedia.p4": "Audio: conversión, cortes y ajustes, efectos de sonido, reverb, normalización y ecualización.",
    "experience.multimedia.p5": "Video: edición dinámica, edición de escenas, ajustes de audio, subtítulos y traducciones asistidas por IA.",
    "experience.multimedia.p6": "Resultados: +7.500 archivos de audio editados y guardados en la nube; +550 videos publicados con subtítulos y traducciones en Portugués, Inglés y Español.",
    
    "experience.sports-trader.title": "Trader Deportivo - Trabajo Freelance en Betfair",
    "experience.sports-trader.date_text": "Marzo 2021 -",
    "experience.sports-trader.date_tag": "Diciembre 2021",
    "experience.sports-trader.p1": "Servicios especializados en operaciones de inversión deportiva, enfocados en análisis estadístico y estrategias inteligentes para maximizar resultados.",
    "experience.sports-trader.p2": "Probabilidad y Estadística aplicadas al fútbol",
    "experience.sports-trader.p3": "Operaciones en la 1ª mitad, 2ª mitad y partido completo",
    "experience.sports-trader.p4": "Análisis de goles (under/over), promedios, porcentajes y minutos decisivos",
    "experience.sports-trader.p5": "Estrategias Back/Lay para favoritos, locales y visitantes",
    "experience.sports-trader.p6": "Análisis previa, en vivo y post-partido",
    "experience.sports-trader.p7": "Herramientas exclusivas: diarios de inversión y calculadora",
    "experience.sports-trader.p8": "Gestión de Bankroll y planes de trading personalizados",
    "experience.sports-trader.p9": "Control emocional y disciplina psicológica",
    "experience.sports-trader.p10": "Estudio avanzado de cuotas (velocidad, intervalo y resistencia)",
    "experience.sports-trader.p11": "Objetivo: ofrecer seguridad, consistencia e inteligencia en la toma de decisiones para inversores deportivos.",
    
    "experience.administrative-assistant.title": "Asistente Administrativo - Centro Universitario Vale Do Ribeira (Univr)",
    "experience.administrative-assistant.date_text": "Julio 2016 -",
    "experience.administrative-assistant.date_tag": "Septiembre 2019",
    "experience.administrative-assistant.p1": "Sector: CTE (Centro de Tecnología Educativa) Actividades principales:",
    "experience.administrative-assistant.p2": "Soporte remoto,",
    "experience.administrative-assistant.p3": "Desarrollo, creación de layout y estandarización visual,",
    "experience.administrative-assistant.p4": "Uso de las principales herramientas tecnológicas (Nube - Drive, YouTube),",
    "experience.administrative-assistant.p5": "Gestión del Entorno Virtual de Aprendizaje (AVA) - Plataforma Moodle.",
    "experience.administrative-assistant.p6": "Elaboración del calendario académico (Urania),",
    "experience.administrative-assistant.p7": "Calendario de actividades extraescolares.",
    "experience.administrative-assistant.p8": "Recepción y envío de correos electrónicos,",
    "experience.administrative-assistant.p9": "Elaboración y control de diversos documentos,",
    "experience.administrative-assistant.p10": "Control de información interna,",
    "experience.administrative-assistant.p11": "Elaboración de hojas de cálculo,",
    "experience.administrative-assistant.p12": "Elaboración de informes,",
    "experience.administrative-assistant.p13": "Asistencia a docentes y estudiantes,",
    "experience.administrative-assistant.p14": "Asistencia directa al Investigador Institucional - responsable de la cumplimentación del Censo de Educación Superior,",
    "experience.administrative-assistant.p15": "Asistencia en el registro y mantenimiento del ENADE,",
    "experience.administrative-assistant.p16": "Otras actividades del día a día.",
    
    "experience.intern-registro.title": "Pasante de Administración - Unidad Regional de Educación de Registro",
    "experience.intern-registro.date_text": "Julio 2014 -",
    "experience.intern-registro.date_tag": "Junio 2016",
    "experience.intern-registro.p1": "Sector: NIET (Núcleo de Información y Tecnología Educativa)",
    "experience.intern-registro.p2": "Experiencia en soporte técnico nivel I, telefónico, remoto (TeamViewer) y servicio de campo.",
    "experience.intern-registro.p3": "Help Desk: WhatsApp Empresarial, Messenger, Blue Talk y otras herramientas (Blue Control y Blue Lab)",
    "experience.intern-registro.p4": "Planificación y desarrollo de proyectos sociales, inclusión digital, informática de bajo nivel y redes sociales.",
    "experience.intern-registro.p5": "Elaboración de actividades relacionadas con la educación, capacitación y gestión de equipos de monitoreo.",
    "experience.intern-registro.p6": "Mantenimiento de computadoras y configuración de redes.",
    
    "experience.intern-miracatu.title": "Pasante de Administración - Unidad Regional de Educación de Miracatu",
    "experience.intern-miracatu.date_text": "Septiembre 2011 -",
    "experience.intern-miracatu.date_tag": "Agosto 2013",
    "experience.intern-miracatu.p1": "Sector: NIET (Núcleo de Información y Tecnología Educativa)",
    "experience.intern-miracatu.p2": "Experiencia en soporte técnico nivel I, telefónico, remoto y servicio de campo.",
    "experience.intern-miracatu.p3": "Help Desk: Messenger, Blue Talk y otras herramientas (Blue Control y Blue Lab)",
    "experience.intern-miracatu.p4": "Planificación y desarrollo de proyectos sociales, inclusión digital, informática de bajo nivel y redes sociales.",
    "experience.intern-miracatu.p5": "Elaboración de actividades relacionadas con la educación, capacitación y gestión de equipos de monitoreo.",
    "experience.intern-miracatu.p6": "Mantenimiento de computadoras y configuración de redes,",
    "experience.intern-miracatu.p7": "Actualización del sitio HTML con software Dreamweaver.",
    
    "experience.cashier-bank.title": "Cajero - Banco Bradesco",
    "experience.cashier-bank.date_text": "Abril 2009 -",
    "experience.cashier-bank.date_tag": "Marzo 2011",
    "experience.cashier-bank.p1": "Actividades realizadas:",
    "experience.cashier-bank.p2": "Apertura y cierre de caja, asegurando precisión en los registros financieros.",
    "experience.cashier-bank.p3": "Control y registro de ingresos y gastos, asegurando organización y transparencia.",
    "experience.cashier-bank.p4": "Envío de correo y documentos de forma responsable y puntual.",
    "experience.cashier-bank.p5": "Procesamiento y recepción de pagos de facturas (agua, electricidad, teléfono, internet y letras de cambio).",
    "experience.cashier-bank.p6": "Asistencia a jubilados, pensionistas y beneficiarios del INSS con retiros y pagos.",
    "experience.cashier-bank.p7": "Gestión de pagos a proveedores, manteniendo un flujo de caja regular.",
    "experience.cashier-bank.p8": "Competencias desarrolladas:",
    "experience.cashier-bank.p9": "Organización y atención al detalle.",
    "experience.cashier-bank.p10": "Responsabilidad en el manejo de efectivo.",
    "experience.cashier-bank.p11": "Servicio al cliente con empatía y eficiencia.",
    "experience.cashier-bank.p12": "Agilidad en procesos administrativos y financieros.",
    
    "experience.general-services.title": "Servicios Generales - Supermercados Tio Beba",
    "experience.general-services.date_text": "Enero 2009 -",
    "experience.general-services.date_tag": "Marzo 2011",
    "experience.general-services.p1": "Amplia experiencia profesional en áreas administrativas, comerciales y operacionales, incluyendo:",
    "experience.general-services.p2": "Servicio al cliente y operaciones financieras: trabajar como cajero en un supermercado y sucursal bancaria representando Bradesco; responsable de abrir y cerrar la caja, enviar bolsas de correo, procesar pagos, retiros y asistir a jubilados y pensionistas del INSS (Instituto Nacional de Seguro Social Brasileño); gestión de pagos a proveedores.",
    "experience.general-services.p3": "Logística y operaciones: organización y reposición del área de ventas; embalaje y verificación de mercancías; apoyo en entregas domiciliarias y carga; verificación de recepción y descarga; despacho de entregas.",
    "experience.general-services.p4": "Ventas y operaciones comerciales: experiencia como vendedor de materiales de construcción, productos agrícolas y electrónica; servicio al cliente; compra y fijación de precios de mercancías; control de inventario y verificación de facturas.",
    "experience.general-services.p5": "Administración y apoyo: gestión de archivos, organización de documentos y apoyo en rutinas administrativas.",
    "experience.general-services.p6": "Competencias desarrolladas:",
    "experience.general-services.p7": "Organización y atención al detalle",
    "experience.general-services.p8": "Competencias desarrolladas:",
    "experience.general-services.p9": "Responsabilidad en el manejo de valores",
    "experience.general-services.p10": "Habilidades interpersonales y servicio al cliente",
    "experience.general-services.p11": "Agilidad en procesos logísticos y administrativos",
    "experience.general-services.p12": "Adaptabilidad a diferentes roles y departamentos",
    
    "education.title": "Educación",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "Octubre 2021 - Presente",
    "education.dio.text": "La mayor plataforma de educación abierta en TI de América Latina, con más de 1 millón de usuarios. DIO se asocia con empresas innovadoras, proporcionando experiencias de aprendizaje inmersivas centradas en la empleabilidad. Principales certificaciones listadas a continuación.",
    "education.univr.mba": "CENTRO UNIVERSITARIO VALE DO RIBEIRA (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.text": "MBA en Gestión y Gobernanza de Tecnología de la Información",
    "education.univr.bachelor": "CENTRO UNIVERSITARIO VALE DO RIBEIRA (UNIVR) - Licenciatura",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.text": "Licenciatura en Administración de Empresas",
    
    "projects.title": "Proyectos",
    "projects.github": "GitHub",
    "projects.github.p1": "Creando una aplicación tipo Canvas con Power Platform",
    "projects.github.p2": "Agregando Seguridad a APIs en AWS con Amazon Cognito",
    "projects.github.p3": "Explorando Rest Assured para la Automatización de Pruebas de API",
    "projects.github.p4": "Profesional de QA: Pruebas Funcionales Manuales",
    "projects.github.p5": "Implementando Pantalla de Login con Validación Usando TypeScript",
    "projects.github.p6": "Desarrollando la Pantalla de Registro de la Plataforma DIO con React",
    "projects.github.p7": "Creando una Wiki de Repositorio de GitHub con React",
    "projects.github.p8": "Identificar Sus Habilidades que Pueden Monetizarse",
    "projects.github.p9": "IA Entrevistador: Su Simulador Inteligente de Entrevistas",
    "projects.github.p10": "IA Mentor de Carrera: Descubra Su Futuro en Tech",
    "projects.github.p11": "Creando una Aplicación de Organización de Finanzas Personales con Vibe Coding",
    "projects.github.p12": "Creando una Calculadora con React",
    "projects.github.p13": "Abstrayendo Formaciones de DIO Usando Orientación a Objetos con Kotlin",
    "projects.github.p14": "Creando un Clon de BuzzFeed con Angular",
    "projects.github.p15": "Creando un Blog con Angular",
    "projects.github.p16": "Construyendo una Pokédex con JavaScript",
    "projects.github.p17": "Creando tu Primera Página de Destino con HTML y CSS",
    "projects.github.p18": "Creando tu Primer Sitio Web Completo con HTML",
    "projects.github.p19": "Creando una Página Web Usando Etiquetas Aprendidas",
    "projects.github.p20": "Creando un Pipeline de CI/CD con Cloud Build y Terraform",
    "projects.github.p21": "Utilizando Cloud Shell",
    "projects.github.p22": "Personalizando el Panel y Cambiando las Preferencias de Idioma",
    "projects.github.p23": "Exportación de Facturación en Google Cloud Platform",
    "projects.github.p24": "Definición de Presupuesto de Facturación en Google Cloud Platform",
    "projects.github.p25": "Diseñando Su Organización de Carpetas y Proyectos y Grupos de Acceso en Google Cloud Platform",
    "projects.github.p26": "Creando un Pipeline de Implementación con GitLab y Kubernetes",
    "projects.github.p27": "Creando una Implementación de Aplicación",
    "projects.github.p28": "Definición de un Clúster Swarm Local con Vagrant",
    "projects.github.p29": "Creando un Contenedor para una Aplicación WEB",
    "projects.github.p30": "Explorando Datos Demográficos con Servicios de Big Data en AWS",
    "projects.github.p31": "Entrenamiento de Redes Neuronales con Transfer Learning",
    "projects.github.p32": "Mejores Prácticas con DynamoDB",
    "projects.github.p33": "Creando Modelos con Python y Machine Learning para Predecir la Evolución del COVID-19 en Brasil",
    "projects.github.p34": "Aplicación Nativa Sobre Fútbol Femenino con Android Jetpack y Java",
    "projects.github.p35": "Creando el Front-end con ReactJS",
    "projects.github.p36": "Aplicación de Reserva DIO",
    "projects.github.p37": "Creando la Interfaz de iFood con React Native",
    "projects.github.p38": "Infraestructura como Código con Serverless Framework en AWS",
    "projects.github.p39": "Creando un Administrador de Naves de Star Wars con SQL Server + .NET",
    "projects.github.p40": "Creando una Aplicación para Conversión y Cambio de Divisas",
    "projects.github.p41": "Desarrollando su Blog con Tecnologías de Java y Angular",
    "projects.github.p42": "Creando una Aplicación de Noticias ReactJS Usando PWA",
    "projects.github.p43": "Creando un Sitio Web para Encontrar Restaurantes Usando Google Maps que Consulta la API de Google",
    "projects.github.p44": "Creando su Ecosistema de Big Data en la Nube",
    "projects.github.p45": "Análisis de Datos con Python y Pandas",
    "projects.github.p46": "Creando un Catálogo de Juegos Usando Mejores Prácticas de Arquitectura con .NET",
    "projects.github.p47": "Construyendo un Proyecto con Arquitectura Basada en Microservicios Usando Spring Cloud",
    "projects.github.p48": "Construyendo un Sistema de Control de Tiempo y Acceso con Spring Boot",
    "projects.github.p49": "Creando un Sistema de Clasificados con Ruby on Rails",
    "projects.github.p50": "MindApp - Desarrollando Cloud Tags con Ruby",
    "projects.github.p51": "Cree un Administrador de Esferas de Dragon Ball Z Usando ReactJS, Jest, React Testing Library y Cypress",
    "projects.github.p52": "Desarrollando SPA con Angular",
    "projects.github.p53": "Creando un Sistema de Presupuesto, Usando CQRS, Quarkus, Kafka e Implementación en EKS",
    "projects.github.p54": "Ejecutando su Aplicación Java en Kubernetes. ¡De la Implementación al Depuración sin Miedo!",
    "projects.github.p55": "Creando una Solución de Comercio Electrónico con Microservicios en Java",
    "projects.github.p56": "Creando su Administrador de Superhéroes de Marvel y DC en una API Reactiva con Spring Boot",
    "projects.github.p57": "Usando Cypress E2E para Probar un Blog en Angular",
    "projects.github.p58": "Creando Proyecto para Consultar Pronóstico del Tiempo vía API",
    "projects.github.p59": "Implementando su Stack de Pruebas Unitarias e Integradas en un Proyecto .NET Crowdfunding",
    "projects.github.p60": "Construyendo un Proyecto de API .NET Integrado con MongoDB",
    "projects.github.p61": "Construyendo un ChatbotFit en Telegram con JavaScript y NodeJS",
    "projects.github.p62": "Construyendo APIs Atractivas Usando Arquitectura Sin Servidor",
    "projects.github.p63": "Tareas en Segundo Plano Utilizando Node.js y Redis",
    "projects.github.p64": "Solicitando Datos de una API de Criptomonedas",
    "projects.github.p65": "Introducción Práctica a TypeScript",
    "projects.github.p66": "Aprendiendo Spring Data JPA en la Práctica con Java",
    "projects.github.p67": "Desafío Técnico Potencial: API de Pago",
    "projects.github.p68": "Construyendo un Sistema de Programación de Tareas con Entity Framework",
    "projects.github.p69": "Creando un Sistema y Abstrayendo un Teléfono Inteligente con OOP en C#",
    "projects.github.p70": "Construyendo un Sistema de Hospedaje de Hotel en C#",
    "projects.github.p71": "Construyendo un Sistema de Estacionamiento con C#",
    "projects.github.p72": "El Papel de las Bases de Datos SQL y NoSQL en la Ingeniería de Datos",
    "projects.github.p73": "Construya un Proyecto de Base de Datos Lógica desde Cero",
    "projects.github.p74": "Construyendo su Primer Proyecto de Base de Datos Lógica",
    "projects.github.p75": "Construyendo un esquema de Base de Datos Conceptual",
    "projects.github.p76": "Refinando un Diseño de Base de Datos Conceptual – COMERCIO ELECTRÓNICO",
    "projects.github.p77": ".Docker: Uso Práctico en el Escenario de Microservicios",
    "projects.github.p78": "Infraestructura como Código - Script de Aprovisionamiento de Servidor Web (Apache)",
    "projects.github.p79": "Infraestructura como Código: Script para Crear Estructura de Usuario, Directorio y Permisos",
    "projects.github.p80": "Realizando Implementación en la Nube de un Conjunto de API Desarrolladas en Spring Boot",
    "projects.github.p81": "Integrando un Backend de Node.js con un Frontend de React para un Comercio Electrónico",
    "projects.github.p82": "Desarrollando un Menú Hamburguesa y Menú Morfing con Transiciones CSS",
    "projects.github.p83": "Construyendo una Aplicación Usando Sensor de Movimiento con React Native",
    "projects.github.p84": "Aprenda a Crear un Sistema de Estacionamiento Usando TypeScript",
    "projects.github.p85": "Cómo Crear un Front-end para un Comercio Electrónico Usando Angular",
    "projects.github.p86": "Desarrollando una Aplicación Web Progresiva con React para Mapear Datos de COVID-19 en Todo el Mundo",
    "projects.github.p87": "Desarrollo de Pruebas Unitarias para Validar una API REST para la Gestión del Inventario de Cerveza",
    "projects.github.p88": "Cree su Administrador de Salas de Reuniones con Java y Angular",
    "projects.github.p89": "Construyendo una API REST para Consultar Ciudades Brasileñas de Cero a Producción",
    "projects.github.p90": "Desarrollando un Sistema de Gestión de Personas en API REST con Spring Boot",
    "projects.github.p91": "Creando tu Juego en Estilo Space Shooter",
    "projects.github.p92": "Creando tu Propio Juego de Tic-Tac-Toe con HTML y Javascript",
    "projects.github.p93": "Desarrollando un Juego de Memoria",
    "projects.github.p94": "Construyendo tu Primer Juego de Naves",
    "projects.github.p95": "Recreando el Famoso Juego del Dinosaurio sin Internet",
    "projects.github.p96": "Creando un Ecosistema Hadoop Completamente Administrado con Google Cloud Dataproc",
    "projects.github.p97": "MySql - Cómo Modelar una Base de Datos de Control de Series Observadas",
    "projects.github.p98": "Simplificando la Creación de Paquetes de Procesamiento de Imágenes en Python",
    "projects.github.p99": "Construyendo un Acortador de URL",
    "projects.github.p100": "Creando un Front-end Totalmente Componentizado en la Práctica con ReactJS",
    "projects.github.p101": "Creando tu Juego de Memoria Estilo Genius",
    "projects.github.p102": "Creando una Aplicación para Mostrar tu Portafolio de GitHub",
    "projects.github.p103": "Crear un Aplicación de Tarjeta de Visita en Kotlin",
    "projects.github.p104": "Creando una Aplicación de Recordatorios y Tareas con Kotlin",
    "projects.github.p105": "Explorando Patrones de Diseño en la Práctica con Java",
    "projects.github.p106": "Abstrayendo un Bootcamp Usando Orientación a Objetos en Java",
    "projects.github.p107": "Creando un Banco Digital con Java y Orientación a Objetos",
    "projects.github.p108": "Abstrayendo un Juego RPG Usando Orientación a Objetos con C#",
    "projects.github.p109": "Recreando el Juego de la Serpiente con JavaScript",
    "projects.github.p110": "Recreando la Interfaz de Netflix",
    "projects.github.p111": "Recreando la Página de Inicio de Instagram",
    "projects.github.p112": "Creando tu Primer Repositorio de GitHub para Compartir tu Progreso",
    "projects.github.p113": "Creando una Aplicación Simple de Registro de Series en .NET",
    "projects.github.p114": "Creando una Aplicación de Transferencia Bancaria con .NET",
    "projects.github.p115": "Creando tu CV Online con HTML y GitHub Pages",
    "projects.github.p116": "Creando Soluciones Robusta en Dynamics 365 con la Extensión del SDK",
    "projects.github.p117": "Documentando y Probando tu API Rest con Kotlin",
    "projects.github.p118": "Contribuyendo a un Proyecto Open Source en GitHub",
    "projects.github.p119": "Simulando una Cuenta Bancaria a Través del Terminal/Consola",
    "projects.github.p120": "Creando un Pequeño Sistema para Validar un Proceso de Selección",
    "projects.github.p121": "Modelando el iPhone con UML: Funciones de Música, Llamadas e Internet",
    
    "footer.social": "Mis Redes Sociales",
    "footer.powered": "Desarrollado con w3.css"
  }
};

/**
 * Apply translations to all elements that have a data-i18n attribute.
 * @param  {string} locale - locale key, e.g. 'en-US'
 */
function applyTranslations(locale) {
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    const text = translations[locale] && translations[locale][key];
    if (text !== undefined) {
      if (el.tagName.toLowerCase() === 'input' || el.tagName.toLowerCase() === 'textarea') {
        el.value = text;
      } else {
        el.textContent = text;
      }
    }
  });

  if (translations[locale] && translations[locale]['meta.title']) {
    document.title = translations[locale]['meta.title'];
  }
}

/* Language selector logic */
const languageSelect = document.getElementById('language-select');

const savedLang = localStorage.getItem('cv_lang') || 'en-US';
languageSelect.value = savedLang;
applyTranslations(savedLang);

languageSelect.addEventListener('change', (e) => {
  const newLang = e.target.value;
  applyTranslations(newLang);
  localStorage.setItem('cv_lang', newLang);
});