const body = document.getElementById('page-body');
const themeToggleBtn = document.getElementById('theme-toggle');
const themeIcon = document.getElementById('theme-icon');

// Initialize theme from localStorage if available
const savedTheme = localStorage.getItem('cv_theme');
if (savedTheme === 'dark') {
  body.classList.add('dark-theme');
  themeIcon.className = 'fa fa-moon-o';
} else {
  body.classList.remove('dark-theme');
  themeIcon.className = 'fa fa-sun-o';
}

// Toggle theme on button click
themeToggleBtn.addEventListener('click', () => {
  const isDark = body.classList.toggle('dark-theme');
  themeIcon.className = isDark ? 'fa fa-moon-o' : 'fa fa-sun-o';
  localStorage.setItem('cv_theme', isDark ? 'dark' : 'light');
});

/* ---------------------------
   Simple translation system
   --------------------------- */

const translations = {
  "en-US": {
    "meta.title": "Nivaldo Beirão - Online CV",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "IT Governance Specialist | GRC & Compliance | Administrative Processes | Strategic Technical Support | Moodle Management Specialist",
    "location": "Remote / Brazil (GMT-3)",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.IT_Management": "IT Management",
    "skills.IT_Governance": "IT Governance",
    "skills.Project-Management": "Project Management",
    "skills.Strategic-Planning": "Strategic Planning",
    "skills.Moodle": "Moodle",
    "skills.Standardized_Work": "Standardized Work",
    "skills.Process_Optimization": "Process Optimization",
    "skills.Financial_Risk_Management": "Financial Risk Management",
    "skills.Compliance_Management": "Compliance Management",
    "skills.Administrative_Support": "Administrative Support",
    "skills.Technical_Support": "Technical Support",
    "skills.Microsoft_Excel": "Microsoft Excel",
    "skills.Calculation": "Calculation",
    "skills.JavaScript": "JavaScript",
    "skills.HTML": "HTML",
    "skills.CSS": "CSS",
    "skills.Banking_Operations": "Banking Operations",
    "skills.Customer_Service": "Customer Service",
    "skills.Internal_Process_Audit": "Internal Process Audit",
    "skills.Inventory_and_Asset_Management": "Inventory and Asset Management",

    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Analytical_Thinking": "Analytical Thinking",
    "skills.Emotional_Intelligence": "Emotional Intelligence",
    "skills.Teamwork": "Teamwork",
    "skills.Organization": "Organization",
    "skills.Resilience": "Resilience",
    "skills.Critical_Thinking": "Critical Thinking",
    "skills.Leadership": "Leadership",
    "skills.People_Management": "People Management",
    
    "languages.title": "Languages",
    "languages.pt": "Portuguese",
    "languages.en": "English",
    "languages.es": "Spanish",
    
    "about.title": "About",
    "about.text": "IT Governance and Management Specialist with a solid background in Business Administration and a focus on Operational Efficiency and GRC (Governance, Risk and Compliance). Experience in developing auditable processes, regulatory compliance and large-scale digital asset management using Artificial Intelligence. Analytical and resilient profile, with a history of technical excellence (Harvard CC50) and a focus on service stability and risk mitigation. Artificial Intelligence: AI in Practice, Prompt Engineering for administrative productivity and process automation. Frameworks: ITIL Fundamentals and Balanced Scorecard (BSC)",
    
    "experience.title": "Experiences",
    "experience.multimedia.title": "Multimedia Editor and Digital Asset Manager - Freelance work on Audacity",
    "experience.multimedia.date_text": "April 2023 -",
    "experience.multimedia.date_tag": "Present",
    "experience.multimedia.p1": "Digital Process Management and Production at Scale.",
    "experience.multimedia.p2": "Responsible for structuring the workflow and technical delivery of digital assets, ensuring 100% compliance with quality standards and deadlines. Strategic use of Artificial Intelligence to optimize translation and editing processes.",
    "experience.multimedia.p3": "Data Governance: Management and organization of a cloud repository with over 8,000 digital assets, ensuring integrity and versioning.",
    "experience.multimedia.p4": "Institutional Standardization: Creation of protocols for subtitling, translation, and audio normalization, ensuring a cohesive visual and sound identity.",
    "experience.multimedia.p5": "Linguistic Compliance: Supervision and technical review of AI-assisted subtitles and translations (PT-BR, EN-US, ES-ES), ensuring communication accuracy.",
    "experience.multimedia.p6": "Operational Efficiency: Implementation of dynamic editing methodologies that resulted in the delivery of over 8,000 audio files and 550 videos with a high standard of finish.",
    
    "experience.sports-trader.title": "Risk Analyst and Market Intelligence - Freelance work on Betfair",
    "experience.sports-trader.date_text": "March 2021 -",
    "experience.sports-trader.date_tag": "December 2021",
    "experience.sports-trader.p1": "Focus Area: Statistical Analysis, GRC (Governance, Risk and Compliance) and Asset Management in Highly Volatile Markets.",
    "experience.sports-trader.p2": "Focus on the development and execution of predictive models based on probability and applied statistics, with rigorous control of operational risks and compliance with market strategies.",
    "experience.sports-trader.p3": "Responsibilities and Governance (GRC):",
    "experience.sports-trader.p4": "Risk and Compliance Modeling: Analysis of complex variables to support strategic decision-making in real time, ensuring the integrity of processes and compliance with established risk models.",
    "experience.sports-trader.p5": "Risk Management (Bankroll Management): Capital management focused on asset preservation and loss mitigation, using audit tools and \"logbooks\" to ensure governance over investments.",
    "experience.sports-trader.p6": "Quantitative Analysis and Pricing: Advanced asset pricing study (ODDs), evaluating volatility and resistance points, ensuring that operations are within acceptable risk metrics.",
    "experience.sports-trader.p7": "Operational Discipline and Auditing: Maintaining high analytical rigor under pressure, ensuring that 100% of strategies followed the pre-established operational governance plan, without deviations in conduct or execution.",
    "experience.sports-trader.p8": "Results and Competencies:",
    "experience.sports-trader.p9": "Data Intelligence: Transforming raw data into investment decisions, using statistical calculators and market trend analysis.",
    "experience.sports-trader.p10": "Resilience and Risk Control: Mastery of bankroll management techniques and psychological control, fundamental for the sustainability of operations in highly uncertain environments.",
    
    "experience.administrative-assistant.title": "Administrative Assistant - Vale Do Ribeira University Center (Univr)",
    "experience.administrative-assistant.date_text": "July 2016 -",
    "experience.administrative-assistant.date_tag": "September 2019",
    "experience.administrative-assistant.p1": "Focus Area: Educational Data Management, GRC (Governance, Risk, and Compliance), and Technological Support for Virtual Environments.",
    "experience.administrative-assistant.p2": "Strategic role in developing technological solutions applied to education, focusing on academic data governance and compliance with federal regulatory standards (MEC).",
    "experience.administrative-assistant.p3": "Responsibilities and Governance (GRC):",
    "experience.administrative-assistant.p4": "Regulatory Data Governance (MEC/ENADE): Direct support to the Institutional Researcher in the collection and processing of data for the Higher Education Census. Guaranteeing the integrity, reliability, and compliance of data reported to the MEC, mitigating risks of institutional irregularities.",
    "experience.administrative-assistant.p5": "Process Management and Auditing: Preparation, control, and management of critical documents and reports in Excel, ensuring compliance with regulatory deadlines and the organization of the academic workflow.",
    "experience.administrative-assistant.p6": "Virtual Learning Environment (VLE) Administration: Management of the Moodle platform, defining security and usability standards for more than 2,500 users.",
    "experience.administrative-assistant.p7": "Flow and Calendar Management: Organization of complex academic schedules (Urânia) and activity calendars via Google Sheets, optimizing the allocation of institutional resources.",
    "experience.administrative-assistant.p8": "Results and Technical Competencies:",
    "experience.administrative-assistant.p9": "Standardization and Scalability: Management of the Moodle LMS with the creation of templates for 27 courses (On-site and Distance Learning), ensuring visual and operational consistency for the institution.",
    "experience.administrative-assistant.p10": "Strategic Support: Provision of specialized technical support to coordinators and faculty, ensuring the operational continuity of synchronous and asynchronous classes.",
    "experience.administrative-assistant.p11": "Institutional Transition: Active participation in the technological transition process from College to University Center, ensuring the conformity of data systems during the expansion to Distance Learning.",
    
    "experience.intern-registro.title": "Business Administration Intern - Regional Education Unit of Registro",
    "experience.intern-registro.date_text": "July 2014 -",
    "experience.intern-registro.date_tag": "July 2016",
    "experience.intern-registro.p1": "Focus Area: Strategic IT Support, GRC (Asset Control and Compliance), and Educational Project Management.",
    "experience.intern-registro.p2": "Work experience at NIET (Educational Information and Technology Center), focused on IT infrastructure and operational data management for the state education network.",
    "experience.intern-registro.p3": "Responsibilities and Governance (GRC/Excel):",
    "experience.intern-registro.p4": "Inventory and Data Management (Intermediate Excel): Creation and maintenance of control spreadsheets for the management of technological assets in 40 school units. Use of search formulas and pivot tables for hardware monitoring and maintenance status.",
    "experience.intern-registro.p5": "IT Compliance and Governance: Ensuring the standardization and security of local networks and mobile devices, ensuring that the use of digital tools was in accordance with the guidelines of the Department of Education.",
    "experience.intern-registro.p6": "Incident Management (Help Desk): Level 1 support (On-site/Remote) via TeamViewer and WhatsApp Business, focusing on quick resolution and incident logging for support auditing.",
    "experience.intern-registro.p7": "Inclusion Project Planning: Assistance in executing schedules and monitoring goals for large-scale technological training programs.",
    "experience.intern-registro.p8": "Results and Competencies:",
    "experience.intern-registro.p9": "Multiplier Training: Direct training and management of over 200 monitors over 2 years, disseminating best practices for information use and security.",
    "experience.intern-registro.p10": "Service Scalability: Active technical support to 40 school units, ensuring the continuity of pedagogical and administrative operations in the region.",

    "experience.intern-miracatu.title": "Business Administration Intern - Regional Education Unit of Miracatu",
    "experience.intern-miracatu.date_text": "August 2011 -",
    "experience.intern-miracatu.date_tag": "August 2013",
    "experience.intern-miracatu.p1": "Focus Area: Strategic IT Support, GRC (Governance, Assets, and Compliance), and Implementation of Educational Solutions.",
    "experience.intern-miracatu.p2": "Work at NIET (Educational Information and Technology Center), focusing on technological infrastructure and process standardization for the state education network.",
    "experience.intern-miracatu.p3": "Responsibilities and Governance (GRC/Excel):",
    "experience.intern-miracatu.p4": "Inventory and Data Management (Intermediate Excel): Creation and control of spreadsheets for managing technological assets of 28 school units. Use of formulas and pivot tables to monitor the hardware lifecycle and maintenance status.",
    "experience.intern-miracatu.p5": "Compliance and Standardization: Ensuring the correct implementation of the Education Department's IT guidelines, guaranteeing that support and infrastructure were in full compliance with institutional standards.",
    "experience.intern-miracatu.p6": "Incident Management and Help Desk: Level 1 technical support (on-site and remote), focused on the rapid resolution of critical problems and the recording of incidents to ensure operational continuity.",
    "experience.intern-miracatu.p7": "Governance in Training: Organization of schedules and materials for technological training, focusing on the dissemination of technical knowledge within school units.",
    "experience.intern-miracatu.p8": "Results and Competencies:",
    "experience.intern-miracatu.p9": "Training of Multipliers: Direct management and training of over 120 monitors, ensuring technological autonomy in schools in the region.",
    "experience.intern-miracatu.p10": "Operational Efficiency: Active and structured technical support to 28 school units, optimizing the use of technological resources and incident management.",
    
    "experience.cashier-bank.title": "Clerk / Cashier - Bradesco Bank",
    "experience.cashier-bank.date_text": "April 2009 -",
    "experience.cashier-bank.date_tag": "March 2011",
    "experience.cashier-bank.p1": "Focus Area: Financial Operations Management, GRC (Governance, Risk and Compliance) and Banking Compliance.",
    "experience.cashier-bank.p2": "Strategic performance in customer service and cash management, with a total focus on accuracy, mitigation of operational risks and compliance with regulatory standards.",
    "experience.cashier-bank.p3": "Responsibilities and Governance (GRC):",
    "experience.cashier-bank.p4": "Cash Flow Control and Risk Management: Responsible for the daily opening, closing and reconciliation of funds, ensuring 100% accuracy in records and acting in the prevention of losses and fraud.",
    "experience.cashier-bank.p5": "Compliance and Asset Processing: Management of payments, taxes and agreements, ensuring the integrity of transactions and compliance with Central Bank guidelines and internal protocols.",
    "experience.cashier-bank.p6": "Critical Support and Process Auditing: Support to INSS beneficiaries and suppliers, performing rigorous document verification to ensure institutional security.",
    "experience.cashier-bank.p7": "Data and Documentation Governance: Control of mailbags and critical documents, ensuring full traceability and organization of the administrative flow according to audit standards.",
    "experience.cashier-bank.p8": "Results and Competencies:",
    "experience.cashier-bank.p9": "Crisis and Transition Management: Active role in the migration of operating systems, ensuring that the technological transition respected governance pillars and did not affect service compliance.",
    "experience.cashier-bank.p10": "Compliance Multiplier: Responsible for training and onboarding new employees, disseminating the culture of safety, ethics, and the institution's GRC rules.",
    "experience.cashier-bank.p11": "Operational Excellence: Recognition for conflict resolution in high-pressure environments and customer loyalty through secure and transparent processes.",
    
    "experience.general-services.title": "Operations and Sales Assistant (Retail) - Tio Beba Supermarkets",
    "experience.general-services.date_text": "January 2009 -",
    "experience.general-services.date_tag": "March 2011",
    "experience.general-services.p1": "Operational Process Management, Inventory, and Cash Flow",
    "experience.general-services.p2": "Multifunctional role focused on organization, asset control, and excellence in customer service, ensuring that company rules are followed with technical and ethical rigor.",
    "experience.general-services.p3": "Responsibilities and Governance:",
    "experience.general-services.p4": "Cash Management: Responsible for cash operations, ensuring 100% accuracy in closings and verification of invoices and mailbags.",
    "experience.general-services.p5": "Logistics and Inventory: Strategic organization of inventory and sales area, optimizing replenishment time and ensuring accuracy in shipment verification.",
    "experience.general-services.p6": "Administrative Versatility: Direct support in purchasing routines, pricing, and file control, maintaining the order of institutional documents.",
    "experience.general-services.p7": "Customer Service and Support: Integration between administrative and commercial areas, focusing on resolving customer problems and providing logistical support (deliveries).",
    "experience.general-services.p8": "Results and Competencies:",
    "experience.general-services.p9": "Operational Efficiency: Guarantee of total compliance in internal cash and inventory audit processes.",
    "experience.general-services.p10": "Agility and Resilience: Ability to adapt to different sectors (commerce, finance, and logistics), maintaining a high standard of delivery under pressure.",
    
    "education.title": "Education",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "October 2021 - Present",
    "education.dio.text": "Largest open IT education platform in Latin America, with over 1 million users. DIO partners with innovative companies, providing immersive learning experiences focused on employability. Main certifications are listed below.",
    "education.univr.mba": "VALE DO RIBEIRA UNIVERSITY CENTER (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.title": "MBA in Information Technology Management and Governance",
    "education.univr.mba.text": "Focus on governance frameworks, technology compliance, and strategic IT asset management. Development of skills in systems auditing, information security, and alignment between technology and business objectives.",
    "education.univr.bachelor": "VALE DO RIBEIRA UNIVERSITY CENTER (UNIVR) - Bachelor's",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.title": "Bachelor's Degree in Business Administration",
    "education.univr.bachelor.text": "Solid background in organizational management, administrative processes, applied law, and finance. Focus on developing a systemic vision and process analysis for operational efficiency.",

    "projects.title": "Projects",
    "projects.github": "GitHub",
    "projects.github.p1": "Creating a Canvas Type Application with Power Platform",
    "projects.github.p2": "Adding Security to APIs in AWS with Amazon Cognito",
    "projects.github.p3": "Exploring Rest Assured for API Test Automation",
    "projects.github.p4": "QA Professional: Manual Functional Testing",
    "projects.github.p5": "Implementing a Login Screen with Validation Using TypeScript",
    "projects.github.p6": "Developing the DIO Platform Registration Screen with React",
    "projects.github.p7": "Creating a GitHub Repository Wiki with React",
    "projects.github.p8": "Identifying Your Skills that Can be Monetized",
    "projects.github.p9": "AI Interviewer: Your Intelligent Interview Simulator",
    "projects.github.p10": "AI Career Mentor: Discover Your Future in Tech",
    "projects.github.p11": "Creating a Personal Finance Organization App with Vibe Coding",
    "projects.github.p12": "Creating a Calculator with React",
    "projects.github.p13": "Abstracting DIO Formations Using Object Orientation with Kotlin",
    "projects.github.p14": "Creating a BuzzFeed Clone with Angular",
    "projects.github.p15": "Creating a Blog with Angular",
    "projects.github.p16": "Building a Pokédex with JavaScript",
    "projects.github.p17": "Creating Your First Landing Page with HTML and CSS",
    "projects.github.p18": "Creating Your First Complete Website with HTML",
    "projects.github.p19": "Creating a Web Page Using Learned Tags",
    "projects.github.p20": "Creating a CI/CD Pipeline with Cloud Build and Terraform",
    "projects.github.p21": "Using Cloud Shell",
    "projects.github.p22": "Customizing Dashboard and Changing Language Preferences",
    "projects.github.p23": "Billing Export in Google Cloud Platform",
    "projects.github.p24": "Defining Billing Budget in Google Cloud Platform",
    "projects.github.p25": "Designing Your Folder and Project Organization and Access Groups in Google Cloud Platform",
    "projects.github.p26": "Creating a Deploy Pipeline with GitLab and Kubernetes",
    "projects.github.p27": "Creating an Application Deploy",
    "projects.github.p28": "Defining a Local Swarm Cluster with Vagrant",
    "projects.github.p29": "Creating a Container for a WEB Application",
    "projects.github.p30": "Exploring Demographics with Big Data Services in AWS",
    "projects.github.p31": "Training Neural Networks with Transfer Learning",
    "projects.github.p32": "Best Practices with DynamoDB",
    "projects.github.p33": "Creating Models with Python and Machine Learning to Predict COVID-19 Evolution in Brazil",
    "projects.github.p34": "Native App About Women's Football with Android Jetpack and Java",
    "projects.github.p35": "Creating the Front-end with ReactJS",
    "projects.github.p36": "Booking App DIO",
    "projects.github.p37": "Creating the iFood Interface with React Native",
    "projects.github.p38": "Infrastructure as Code with Serverless Framework on AWS",
    "projects.github.p39": "Creating a Star Wars Spacecraft Manager with SQL Server + .NET",
    "projects.github.p40": "Creating an Application for Currency Conversion and Exchange",
    "projects.github.p41": "Developing Your Blog with Java and Angular Technologies",
    "projects.github.p42": "Creating a ReactJS News Application Using PWA",
    "projects.github.p43": "Creating a Website to Find Restaurants Using Google Maps that Queries Google API",
    "projects.github.p44": "Creating Your Big Data Ecosystem in the Cloud",
    "projects.github.p45": "Data Analysis with Python and Pandas",
    "projects.github.p46": "Creating a Game Catalog Using Best Architecture Practices with .NET",
    "projects.github.p47": "Building a Project with Architecture Based on Microservices Using Spring Cloud",
    "projects.github.p48": "Building a Time and Access Control System with Spring Boot",
    "projects.github.p49": "Creating a Classifieds System with Ruby on Rails",
    "projects.github.p50": "MindApp - Developing Cloud Tags with Ruby",
    "projects.github.p51": "Create a Dragon Ball Z Sphere Manager Using ReactJS, Jest, React Testing Library and Cypress",
    "projects.github.p52": "Developing SPA with Angular",
    "projects.github.p53": "Creating a Budget System, Using CQRS, Quarkus, Kafka and Deploy on EKS",
    "projects.github.p54": "Running Your Java Application on Kubernetes. From Deploy to Debug without Fear!",
    "projects.github.p55": "Creating an E-commerce Solution with Microservices in Java",
    "projects.github.p56": "Creating Your Marvel and DC Super Heroes Manager in a Reactive API with Spring Boot",
    "projects.github.p57": "Using Cypress E2E to Test a Blog in Angular",
    "projects.github.p58": "Creating Project to Query Weather Forecast via API",
    "projects.github.p59": "Implementing Your Unit and Integration Testing Stack in a .NET Crowdfunding Project",
    "projects.github.p60": "Building a .NET API Project Integrated with MongoDB",
    "projects.github.p61": "Building a ChatbotFit on Telegram with JavaScript and NodeJS",
    "projects.github.p62": "Building Sexy APIs Using Serverless Architecture",
    "projects.github.p63": "Background Tasks Using Node.js and Redis",
    "projects.github.p64": "Requesting Data from a Cryptocurrency API",
    "projects.github.p65": "Practical Introduction to TypeScript",
    "projects.github.p66": "Learning Spring Data JPA in Practice with Java",
    "projects.github.p67": "Tech Potential Challenge: Payment API",
    "projects.github.p68": "Building a Task Scheduling System with Entity Framework",
    "projects.github.p69": "Creating a System and Abstracting a Smartphone with OOP in C#",
    "projects.github.p70": "Building a Hotel Hosting System in C#",
    "projects.github.p71": "Building a Parking System with C#",
    "projects.github.p72": "The Role of SQL and NoSQL Databases in Data Engineering",
    "projects.github.p73": "Build a Logical Database Project from Scratch",
    "projects.github.p74": "Building Your First Logical Database Project",
    "projects.github.p75": "Building a Conceptual Database Schema",
    "projects.github.p76": "Refining a Conceptual Database Design – E-COMMERCE",
    "projects.github.p77": ".Docker: Practical Use in the Microservices Scenario",
    "projects.github.p78": "Infrastructure as Code - Web Server Provisioning Script (Apache)",
    "projects.github.p79": "Infrastructure as Code: Script for Creating User, Directory Structure and Permissions",
    "projects.github.p80": "Performing Cloud Deploy of a Set of APIs Developed in Spring Boot",
    "projects.github.p81": "Integrating a Node.js Backend with a React Frontend for an E-commerce",
    "projects.github.p82": "Developing a Hamburger Menu and Morphing Menu with CSS Transitions",
    "projects.github.p83": "Building an App Using Motion Sensor with React Native",
    "projects.github.p84": "Learn to Create a Parking System Using TypeScript",
    "projects.github.p85": "How to Create a Front-end for an E-commerce Using Angular",
    "projects.github.p86": "Developing a Progressive Web Application with React to Map COVID-19 Data Around the World",
    "projects.github.p87": "Development of Unit Tests to Validate a REST API for Beer Inventory Management",
    "projects.github.p88": "Create Your Meeting Room Manager with Java and Angular",
    "projects.github.p89": "Building a REST API for Querying Brazilian Cities from Zero to Production",
    "projects.github.p90": "Developing a People Management System in REST API with Spring Boot",
    "projects.github.p91": "Creating Your Game in Space Shooter Style",
    "projects.github.p92": "Creating Your Own Tic-Tac-Toe Game with HTML and Javascript",
    "projects.github.p93": "Developing a Memory Game",
    "projects.github.p94": "Building Your First Spaceship Game",
    "projects.github.p95": "Recreating the Famous Dinosaur Game without Internet",
    "projects.github.p96": "Creating a Fully Managed Hadoop Ecosystem with Google Cloud Dataproc",
    "projects.github.p97": "MySql - How to Model a Watched Series Control Database",
    "projects.github.p98": "Simplifying the Creation of Image Processing Packages in Python",
    "projects.github.p99": "Building a URL Shortener",
    "projects.github.p100": "Creating a Fully Componentized Front-end in Practice with ReactJS",
    "projects.github.p101": "Creating Your Memory Game Genius Style",
    "projects.github.p102": "Creating an App to Showcase Your GitHub Portfolio",
    "projects.github.p103": "Creating a Business Card App in Kotlin",
    "projects.github.p104": "Creating a Reminders and Tasks App with Kotlin",
    "projects.github.p105": "Exploring Design Patterns in Practice with Java",
    "projects.github.p106": "Abstracting a Bootcamp Using Object Orientation in Java",
    "projects.github.p107": "Creating a Digital Bank with Java and Object Orientation",
    "projects.github.p108": "Abstracting an RPG Game Using Object Orientation with C#",
    "projects.github.p109": "Recreating the Snake Game with JavaScript",
    "projects.github.p110": "Recreating the Netflix Interface",
    "projects.github.p111": "Recreating Instagram's Homepage",
    "projects.github.p112": "Creating Your First GitHub Repository to Share Your Progress",
    "projects.github.p113": "Creating a Simple Series Registration App in .NET",
    "projects.github.p114": "Creating a Bank Transfer Application with .NET",
    "projects.github.p115": "Creating Your Online CV With HTML and GitHub Pages",
    "projects.github.p116": "Creating Robust Solutions in Dynamics 365 with the SDK Extension",
    "projects.github.p117": "Documenting and Testing Your REST API with Kotlin",
    "projects.github.p118": "Contributing to an Open Source Project on GitHub",
    "projects.github.p119": "Simulating a Bank Account Through the Terminal/Console",
    "projects.github.p120": "Creating a Small System for Validation of a Selection Process",
    "projects.github.p121": "Modeling the iPhone with UML: Music, Calls and Internet Functions",
    "projects.github.p122": "Publishing Your REST API in the Cloud Using Spring Boot 3, Java 17 and Railway",
    "projects.github.p123": "Recreating the PlayStation Store Interface with Angular",
    "projects.github.p124": "Exploring Generative AI in an ETL Pipeline with Python",
    "projects.github.p125": "Creating a Sales Management Report with Power BI",
    "projects.github.p126": "Creating a corporate dashboard with integration to MySQL and Azure",
    "projects.github.p127": "Customizing the Database with Indexes and Procedures",
    "projects.github.p128": "Customizing Access and Automating Actions in MySQL",
    "projects.github.p129": "Creating Transactions, Performing Database Backup and Recovery",
    "projects.github.p130": "Analyzing data from a Sales Dashboard in Power BI",
    "projects.github.p131": "Sales Dashboard with Power BI using Star Schema",
    "projects.github.p132": "Modeling an E-commerce Dashboard with Power BI Using DAX Formulas",
    "projects.github.p133": "Creating a Management Dashboard for Decision Making with Power BI",
    "projects.github.p134": "Creating a Sales and Profit Report with Data Analytics using Power BI",
    "projects.github.p135": "Creating Dynamic Reports using Parameters in Power BI",
    "projects.github.p136": "Creating and Using Your Cryptocurrency Wallet",
    "projects.github.p137": "Creating Your First Cryptocurrency on the Ethereum Network",
    "projects.github.p138": "Create your own Pokémon NFT with Blockchain.",
    "projects.github.p139": "Creating Your First Token from Scratch with Web3 Standards",
    "projects.github.p140": "Creating an NFT in Practice",
    "projects.github.p141": "Creating a Decentralized Autonomous Organization using Web3 Standards",
    "projects.github.p142": "Recreating Wikipedia with a Modern Layout",
    "projects.github.p143": "Cloning a YouTube Page with CSS",
    "projects.github.p144": "Reproducing a YouTube listing with Grid Layout in CSS",
    "projects.github.p145": "Building a Responsive Layout for the Discord Website Using CSS",
    "projects.github.p146": "Cloning the HBO Max Website with HTML and CSS Animations",
    "projects.github.p147": "Publishing Your Professional Portfolio on GitHub Pages",
    "projects.github.p148": "Creating Your Personal Blog with Next.js",
    "projects.github.p149": "Creating an ID Card for the Minecraft Creeper Using Lua",
    
    "footer.social": "My Social Networks",
    "footer.powered": "Powered by w3.css"
  },

  "pt-BR": {
    "meta.title": "Nivaldo Beirão - CV Online",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "Especialista em Governança e Gestão de TI | GRC & Compliance | Processos Administrativos | Suporte Técnico Estratégico | Especialista em Gestão do Moodle",
    "location": "Remoto / Brasil (GMT-3)",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.IT_Management": "Gestão de TI",
    "skills.IT_Governance": "Governança de TI",
    "skills.Project-Management": "Gestão de Projetos",
    "skills.Strategic-Planning": "Planejamento Estratégico",
    "skills.Moodle": "Moodle",
    "skills.Standardized_Work": "Trabalho Padronizado",
    "skills.Process_Optimization": "Otimização de Processos",
    "skills.Financial_Risk_Management": "Gestão de Riscos Financeiros",
    "skills.Compliance_Management": "Gestão de Conformidade",
    "skills.Administrative_Support": "Suporte Administrativo",
    "skills.Technical_Support": "Suporte Técnico",
    "skills.Microsoft_Excel": "Microsoft Excel",
    "skills.Calculation": "Cálculo",
    "skills.JavaScript": "JavaScript",
    "skills.HTML": "HTML",
    "skills.CSS": "CSS",
    "skills.Banking_Operations": "Operações Bancárias",
    "skills.Customer_Service": "Atendimento ao Cliente",
    "skills.Internal_Process_Audit": "Auditoria de Processos Internos",
    "skills.Inventory_and_Asset_Management": "Gestão de Estoque e Ativos",
    
    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Analytical_Thinking": "Pensamento Analítico",
    "skills.Emotional_Intelligence": "Inteligência Emocional",
    "skills.Teamwork": "Trabalho em Equipe",
    "skills.Organization": "Organização",
    "skills.Resilience": "Resiliência",
    "skills.Critical_Thinking": "Senso Crítico",
    "skills.Leadership": "Liderança",
    "skills.People_Management": "Gestão de Pessoas",
    
    "languages.title": "Idiomas",
    "languages.pt": "Português",
    "languages.en": "Inglês",
    "languages.es": "Espanhol",
    
    "about.title": "Sobre",
    "about.text": "Especialista em Governança e Gestão de TI com sólida formação em Administração de Empresas e foco em Eficiência Operacional e GRC (Governança, Risco e Compliance). Experiência no desenvolvimento de processos auditáveis, conformidade regulatória e gestão de ativos digitais em larga escala utilizando Inteligência Artificial. Perfil analítico e resiliente, com histórico de excelência técnica (Harvard CC50) e foco na estabilidade do serviço e mitigação de riscos. Inteligência Artificial: IA na Prática, Prompt Engineering para produtividade administrativa e automação de processos. Frameworks: ITIL Fundamentals e Balanced Scorecard (BSC)",
    
    "experience.title": "Experiências",
    "experience.multimedia.title": "Editor Multimídia e Gerente de Ativos Digitais - Trabalho Freelance com Audacity",
    "experience.multimedia.date_text": "Abril 2023 -",
    "experience.multimedia.date_tag": "Presente",
    "experience.multimedia.p1": "Gestão de Processos Digitais e Produção em Larga Escala.",
    "experience.multimedia.p2": "Responsável por estruturar o fluxo de trabalho e a entrega técnica de ativos digitais, garantindo 100% de conformidade com os padrões de qualidade e prazos. Uso estratégico de Inteligência Artificial para otimizar processos de tradução e edição.",
    "experience.multimedia.p3": "Governança de Dados: Gerenciamento e organização de um repositório em nuvem com mais de 8.000 ativos digitais, garantindo integridade e versionamento.",
    "experience.multimedia.p4": "Padronização Institucional: Criação de protocolos para legendagem, tradução e normalização de áudio, garantindo uma identidade visual e sonora coesa.",
    "experience.multimedia.p5": "Conformidade Linguística: Supervisão e revisão técnica de legendas e traduções assistidas por IA (PT-BR, EN-US, ES-ES), garantindo a precisão da comunicação.",    
    "experience.multimedia.p6": "Eficiência Operacional: Implementação de metodologias de edição dinâmicas que resultaram na entrega de mais de 8.000 arquivos de áudio e 550 vídeos com alto padrão de acabamento.",
    
    "experience.sports-trader.title": "Analista de Risco e Inteligência de Mercado - Trabalho Freelance na Betfair",
    "experience.sports-trader.date_text": "Março 2021 -",
    "experience.sports-trader.date_tag": "Dezembro 2021",
    "experience.sports-trader.p1": "Área de Atuação: Análise Estatística, GRC (Governança, Risco e Compliance) e Gestão de Ativos em Mercados Altamente Voláteis.",
    "experience.sports-trader.p2": "Foco no desenvolvimento e execução de modelos preditivos baseados em probabilidade e estatística aplicada, com rigoroso controle de riscos operacionais e conformidade com estratégias de mercado.",
    "experience.sports-trader.p3": "Responsabilidades e Governança (GRC):",
    "experience.sports-trader.p4": "Modelagem de Risco e Conformidade: Análise de variáveis complexas para apoiar a tomada de decisão estratégica em tempo real, garantindo a integridade dos processos e conformidade com os modelos de risco estabelecidos.",
    "experience.sports-trader.p5": "Gestão de Riscos (Bankroll Management): Gestão de capital focada na preservação de ativos e mitigação de perdas, utilizando ferramentas de auditoria e \"logbooks\" para garantir governança sobre os investimentos.",
    "experience.sports-trader.p6": "Análise Quantitativa e Precificação: Estudo avançado de precificação de ativos (ODDs), avaliando volatilidade e pontos de resistência, garantindo que as operações estejam dentro de métricas de risco aceitáveis.",
    "experience.sports-trader.p7": "Disciplina Operacional e Auditoria: Manutenção de alto rigor analítico sob pressão, garantindo que 100% das estratégias seguissem o plano de governança operacional pré-estabelecido, sem desvios de conduta ou execução.",
    "experience.sports-trader.p8": "Resultados e Competências:",
    "experience.sports-trader.p9": "Inteligência de Dados: Transformação de dados brutos em decisões de investimento, utilizando calculadoras estatísticas e análise de tendências de mercado.",
    "experience.sports-trader.p10": "Resiliência e Controle de Riscos: Domínio de técnicas de gestão de bankroll e controle psicológico, fundamentais para a sustentabilidade das operações em ambientes altamente incertos.",
    
    "experience.administrative-assistant.title": "Assistente Administrativo - Centro Universitário Vale Do Ribeira (Univr)",
    "experience.administrative-assistant.date_text": "Julho 2016 -",
    "experience.administrative-assistant.date_tag": "Setembro 2019",
    "experience.administrative-assistant.p1": "Área de Atuação: Gestão de Dados Educacionais, GRC (Governança, Risco e Compliance) e Suporte Tecnológico para Ambientes Virtuais.",
    "experience.administrative-assistant.p2": "Papel estratégico no desenvolvimento de soluções tecnológicas aplicadas à educação, com foco na governança de dados acadêmicos e conformidade com padrões regulatórios federais (MEC).",
    "experience.administrative-assistant.p3": "Responsabilidades e Governança (GRC):",
    "experience.administrative-assistant.p4": "Governança de Dados Regulatória (MEC/ENADE): Suporte direto ao Pesquisador Institucional na coleta e processamento de dados para o Censo da Educação Superior. Garantia da integridade, confiabilidade e conformidade dos dados reportados ao MEC, mitigando riscos de irregularidades institucionais.",
    "experience.administrative-assistant.p5": "Gestão de Processos e Auditoria: Preparação, controle e gestão de documentos e relatórios críticos em Excel, garantindo conformidade com prazos regulatórios e organização do fluxo acadêmico.",
    "experience.administrative-assistant.p6": "Administração de Ambiente Virtual de Aprendizagem (AVA): Gestão da plataforma Moodle, definindo padrões de segurança e usabilidade para mais de 2.500 usuários.",
    "experience.administrative-assistant.p7": "Gestão de Fluxo e Calendário: Organização de cronogramas acadêmicos complexos (Urânia) e calendários de atividades via Google Sheets, otimizando a alocação de recursos institucionais.",
    "experience.administrative-assistant.p8": "Resultados e Competências Técnicas:",
    "experience.administrative-assistant.p9": "Padronização e Escalabilidade: Gestão do LMS Moodle com a criação de templates para 27 cursos (Presencial e EAD), garantindo consistência visual e operacional para a instituição.",
    "experience.administrative-assistant.p10": "Suporte Estratégico: Fornecimento de suporte técnico especializado a coordenadores e corpo docente, garantindo a continuidade operacional das aulas síncronas e assíncronas.",
    "experience.administrative-assistant.p11": "Transição Institucional: Participação ativa no processo de transição tecnológica de Faculdade para Centro Universitário, garantindo a conformidade dos sistemas de dados durante a expansão para o Ensino a Distância.",
    
    "experience.intern-registro.title": "Estagiário em Administração - Unidade Regional de Educação de Registro",
    "experience.intern-registro.date_text": "Julho 2014 -",
    "experience.intern-registro.date_tag": "Julho 2016",
    "experience.intern-registro.p1": "Área de Atuação: Suporte Técnico Estratégico, GRC (Controle de Ativos e Conformidade) e Gestão de Projetos Educacionais.",
    "experience.intern-registro.p2": "Experiência de trabalho no NIET (Núcleo de Informação e Tecnologia Educacional), focada em infraestrutura de TI e gestão de dados operacionais para a rede estadual de ensino.",
    "experience.intern-registro.p3": "Responsabilidades e Governança (GRC/Excel):",
    "experience.intern-registro.p4": "Inventário e Gestão de Dados (Excel Intermediário): Criação e manutenção de planilhas de controle para a gestão de ativos tecnológicos em 40 unidades escolares. Uso de fórmulas de busca e tabelas dinâmicas para monitoramento de hardware e status de manutenção.",
    "experience.intern-registro.p5": "Conformidade e Governança de TI: Garantia da padronização e segurança das redes locais e dispositivos móveis, assegurando que o uso das ferramentas digitais estivesse em conformidade com as diretrizes da Secretaria da Educação.",
    "experience.intern-registro.p6": "Gerenciamento de Incidentes (Help Desk): Suporte nível 1 (Presencial/Remoto) via TeamViewer e WhatsApp Business, com foco na rápida resolução e registro de incidentes para auditoria de suporte.",
    "experience.intern-registro.p7": "Planejamento de Projetos de Inclusão: Auxílio na execução de cronogramas e monitoramento de metas para programas de treinamento tecnológico em larga escala.",
    "experience.intern-registro.p8": "Resultados e Competências:",
    "experience.intern-registro.p9": "Treinamento de Multiplicadores: Treinamento direto e gestão de mais de 200 monitores ao longo de 2 anos, disseminando boas práticas para o uso da informação e segurança.",
    "experience.intern-registro.p10": "Escalabilidade do Atendimento: Suporte técnico ativo a 40 unidades escolares, garantindo a continuidade das operações pedagógicas e administrativas na região.",
    
    "experience.intern-miracatu.title": "Estagiário em Administração - Unidade Regional de Educação de Miracatu",
    "experience.intern-miracatu.date_text": "Agosto 2011 -",
    "experience.intern-miracatu.date_tag": "Agosto 2013",
    "experience.intern-miracatu.p1": "Área de Atuação: Suporte Estratégico em TI, GRC (Governança, Ativos e Conformidade) e Implementação de Soluções Educacionais.",
    "experience.intern-miracatu.p2": "Trabalho no NIET (Núcleo de Informação e Tecnologia Educacional), com foco em infraestrutura tecnológica e padronização de processos para a rede estadual de ensino.",
    "experience.intern-miracatu.p3": "Responsabilidades e Governança (GRC/Excel):",
    "experience.intern-miracatu.p4": "Inventário e Gestão de Dados (Excel Intermediário): Criação e controle de planilhas para gestão de ativos tecnológicos de 28 unidades escolares. Uso de fórmulas e tabelas dinâmicas para monitoramento do ciclo de vida do hardware e status de manutenção.",
    "experience.intern-miracatu.p5": "Conformidade e Padronização: Garantia da correta implementação das diretrizes de TI da Secretaria da Educação, assegurando que o suporte e a infraestrutura estivessem em total conformidade com os padrões institucionais.",
    "experience.intern-miracatu.p6": "Gerenciamento de Incidentes e Help Desk: Suporte técnico nível 1 (presencial e remoto), focado na rápida resolução de problemas críticos e registro de incidentes para garantir a continuidade operacional.",
    "experience.intern-miracatu.p7": "Governança em Treinamento: Organização de cronogramas e materiais para treinamentos tecnológicos, com foco na disseminação do conhecimento técnico dentro das unidades escolares.",
    "experience.intern-miracatu.p8": "Resultados e Competências:",
    "experience.intern-miracatu.p9": "Treinamento de Multiplicadores: Gestão direta e treinamento de mais de 120 monitores, garantindo autonomia tecnológica nas escolas da região.",
    "experience.intern-miracatu.p10": "Eficiência Operacional: Suporte técnico ativo e estruturado para 28 unidades escolares, otimizando o uso dos recursos tecnológicos e a gestão de incidentes.",
    
    "experience.cashier-bank.title": "Escriturário / Operador de Caixa - Banco Bradesco",
    "experience.cashier-bank.date_text": "Abril 2009 -",
    "experience.cashier-bank.date_tag": "Março 2011",
    "experience.cashier-bank.p1": "Foco de Atuação: Gestão de Operações Financeiras, GRC (Governança, Riscos e Conformidade) e Compliance Bancário.",
    "experience.cashier-bank.p2": "Atuação estratégica no atendimento ao público e gestão de numerário, com foco total em precisão, mitigação de riscos operacionais e cumprimento de normas regulatórias.",
    "experience.cashier-bank.p3": "Responsabilidades e Governança (GRC):",
    "experience.cashier-bank.p4": "Controle de Fluxo de Caixa e Gestão de Riscos: Responsável pela abertura, fechamento e reconciliação diária dos fundos, garantindo 100% de precisão nos registros e atuando na prevenção de perdas e fraudes.",
    "experience.cashier-bank.p5": "Compliance e Processamento de Ativos: Gestão de pagamentos, tributos e acordos, assegurando a integridade das transações e conformidade com as diretrizes do Banco Central e protocolos internos.",
    "experience.cashier-bank.p6": "Suporte Crítico e Auditoria de Processos: Suporte a beneficiários do INSS e fornecedores, realizando rigorosa verificação documental para garantir a segurança institucional.",
    "experience.cashier-bank.p7": "Governança de Dados e Documentação: Controle de malotes e documentos críticos, garantindo total rastreabilidade e organização do fluxo administrativo conforme padrões de auditoria.",
    "experience.cashier-bank.p8": "Resultados e Competências:",
    "experience.cashier-bank.p9": "Gestão de Crise e Transição: Atuação ativa na migração de sistemas operacionais, garantindo que a transição tecnológica respeitasse os pilares de governança e não afetasse a conformidade do atendimento.",
    "experience.cashier-bank.p10": "Multiplicador de Compliance: Responsável pelo treinamento e onboarding de novos colaboradores, disseminando a cultura de segurança, ética e as regras de GRC da instituição.",
    "experience.cashier-bank.p11": "Excelência Operacional: Reconhecimento por resolução de conflitos em ambientes de alta pressão e fidelização de clientes por meio de processos seguros e transparentes.",
    
    "experience.general-services.title": "Assistente de Operações e Vendas (Varejo) - Supermercados Tio Beba",
    "experience.general-services.date_text": "Janeiro 2009 -",
    "experience.general-services.date_tag": "Março 2011",
    "experience.general-services.p1": "Gestão de Processos Operacionais, Estoque e Fluxo de Caixa",
    "experience.general-services.p2": "Atuação multifuncional focada na organização, controle de ativos e excelência no atendimento, garantindo que as regras da empresa fossem seguidas com rigor técnico e ético.",
    "experience.general-services.p3": "Responsabilidades e Governança:",
    "experience.general-services.p4": "Gestão de Numerário: Responsável por operações de caixa, garantindo 100% de precisão nos fechamentos e na conferência de notas fiscais e malotes.",
    "experience.general-services.p5": "Logística e Inventário: Organização estratégica do estoque e área de vendas, otimizando o tempo de reposição e garantindo a acurácia na conferência de remessas.",
    "experience.general-services.p6": "Polivalência Administrativa: Apoio direto em rotinas de compras, precificação e controle de arquivos, mantendo a ordem dos documentos institucionais.",
    "experience.general-services.p7": "Atendimento e Suporte: Integração entre as áreas administrativa e comercial, com foco na resolução de problemas dos clientes e suporte logístico (entregas).",
    "experience.general-services.p8": "Resultados e Competências:",
    "experience.general-services.p9": "Eficiência Operacional: Garantia de conformidade total em processos de auditoria interna de caixa e estoque.",
    "experience.general-services.p10": "Agilidade e Resiliência: Capacidade de adaptação a diferentes setores (comércio, finanças e logística), mantendo o alto padrão de entrega sob pressão.",
    
    "education.title": "Educação",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "Outubro 2021 - Presente",
    "education.dio.text": "Maior plataforma de educação aberta em TI da América Latina, com mais de 1 milhão de usuários. A DIO faz parcerias com empresas inovadoras, oferecendo experiências de aprendizagem imersivas com foco em empregabilidade. Principais certificações listadas abaixo.",
    "education.univr.mba": "CENTRO UNIVERSITÁRIO VALE DO RIBEIRA (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.title": "MBA em Gestão e Governança de Tecnologia da Informação",
    "education.univr.mba.text": "Foco em frameworks de governança, compliance tecnológico e gestão estratégica de ativos de TI. Desenvolvimento de competências em auditoria de sistemas, segurança da informação e alinhamento entre tecnologia e objetivos de negócio.",
    "education.univr.bachelor": "CENTRO UNIVERSITÁRIO VALE DO RIBEIRA (UNIVR) - Bacharelado",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.title": "Bacharel em Administração de Empresas",
    "education.univr.bachelor.text": "Sólida experiência em gestão organizacional, processos administrativos, direito aplicado e finanças. Foco no desenvolvimento de uma visão sistêmica e análise de processos para eficiência operacional.",

    "projects.title": "Projetos",
    "projects.github": "GitHub",
    "projects.github.p1": "Criando um aplicativo do tipo Canvas com a Power Platform",
    "projects.github.p2": "Adicionando Segurança em APIs na AWS com Amazon Cognito",
    "projects.github.p3": "Explorando o Rest Assured Para a Automação de Testes de API",
    "projects.github.p4": "O Dia a Dia de um QA: A Prática de Testes Manuais Funcionais",
    "projects.github.p5": "Implementando Uma Tela de Login Com Validação Usando TypeScript",
    "projects.github.p6": "Desenvolvendo a Tela de Cadastro da Plataforma Dio com React",
    "projects.github.p7": "Criando Uma Wiki de Repositórios do GitHub Com React",
    "projects.github.p8": "Identificando suas Habilidades que Podem ser Remuneradas",
    "projects.github.p9": "IA Entrevistador: Seu Simulador Inteligente de Entrevistas",
    "projects.github.p10": "IA Mentor de Carreira: Descubra Seu Futuro em Tech",
    "projects.github.p11": "Criando um APP de Organização de Finanças Pessoais com Vibe Coding",
    "projects.github.p12": "Criando Uma Calculadora Com React",
    "projects.github.p13": "Abstraindo Formações da DIO Usando Orientação a Objetos com Kotlin",
    "projects.github.p14": "Criando um Clone do BuzzFeed com Angular",
    "projects.github.p15": "Criando um Blog com Angular",
    "projects.github.p16": "Construindo uma Pokédex com JavaScript",
    "projects.github.p17": "Criando sua Primeira Landing Page com HTML e CSS",
    "projects.github.p18": "Criando seu Primeiro Site Completo com HTML",
    "projects.github.p19": "Criar Uma Página Web Utilizando as Tags Aprendidas",
    "projects.github.p20": "Criando Pipeline de CI/CD com Cloud Build e Terraform",
    "projects.github.p21": "Utilizando o Cloud Shell",
    "projects.github.p22": "Personalizando Dashboard e Trocando as Preferências de Idioma",
    "projects.github.p23": "Exportação do Billing na Google Cloud Platform",
    "projects.github.p24": "Definição de Orçamento de Billing na Google Cloud Platform",
    "projects.github.p25": "Desenhando Sua Organização de Pastas e Projetos e Grupos de Acessos na Google Cloud Platform",
    "projects.github.p26": "Criando um Pipeline de Deploy com GitLab e Kubernetes",
    "projects.github.p27": "Criando um Deploy de uma Aplicação",
    "projects.github.p28": "Definição de um Cluster Swarm Local com o Vagrant",
    "projects.github.p29": "Criando um Container de uma Aplicação WEB",
    "projects.github.p30": "Explorando Dados Demográficos com Serviços de Big Data na AWS",
    "projects.github.p31": "Treinamento de Redes Neurais com Transfer Learning",
    "projects.github.p32": "Boas práticas com DynamoDB",
    "projects.github.p33": "Criando Modelos com Python e Machine Learning para Prever a Evolução do COVID-19 no Brasil",
    "projects.github.p34": "App Nativo Sobre Futebol Feminino com Android Jetpack e Java",
    "projects.github.p35": "Criando o Front-end com ReactJS",
    "projects.github.p36": "Booking App DIO",
    "projects.github.p37": "Criando a Interface do iFood com React Native",
    "projects.github.p38": "Infraestrutura Como Código com Serverless Framework na AWS",
    "projects.github.p39": "Criando um Gerenciador de Espaçonaves do Star Wars com SQL Server + .NET",
    "projects.github.p40": "Criando um Aplicativo para Conversão de Moedas e Câmbio",
    "projects.github.p41": "Desenvolvendo seu Blog com as Tecnologias de Java e Angular",
    "projects.github.p42": "Criando uma Aplicação ReactJS de Notícias Utilizando PWA",
    "projects.github.p43": "Criando um Site para Encontrar Restaurantes Usando Google Maps que Consulta API do Google",
    "projects.github.p44": "Criando seu Ecossistema de Big Data na Nuvem",
    "projects.github.p45": "Análise de dados com Python e Pandas",
    "projects.github.p46": "Criando um Catálogo de Jogos Usando Boas Práticas de Arquitetura com .NET",
    "projects.github.p47": "Construindo um Projeto com Arquitetura Baseada em Microsserviços Usando Spring Cloud",
    "projects.github.p48": "Construindo um Sistema de Controle de Ponto e Acesso com Spring Boot",
    "projects.github.p49": "Criando um Sistema de Classificados com Ruby on Rails",
    "projects.github.p50": "MindApp - Desenvolvendo uma Cloud Tags com Ruby",
    "projects.github.p51": "Crie um Gerenciador de Esferas do Dragon Ball Z Usando ReactJS, Jest, React Testing Library e Cypress",
    "projects.github.p52": "Desenvolvendo SPA com Angular",
    "projects.github.p53": "Criando um Sistema de Orçamento, Utilizando CQRS, Quarkus, Kafka e Deploy no EKS",
    "projects.github.p54": "Rodando sua Aplicação Java no Kubernetes. Do Deploy ao Debug sem Medo!",
    "projects.github.p55": "Criando uma Solução de E-commerce com Microsserviços em Java",
    "projects.github.p56": "Criando seu Gerenciador de Super Heróis da Marvel e da DC em uma API Reativa com Spring Boot",
    "projects.github.p57": "Utilizando o Cypress E2E para testar um Blog em Angular",
    "projects.github.p58": "Criando Projeto para Consultar a Previsão do Tempo via API",
    "projects.github.p59": "Implementando sua Stack de Testes de Unidade e Integrados em um Projeto .NET de Crowdfunding",
    "projects.github.p60": "Construindo um Projeto de uma API.NET Integrada ao MongoDB",
    "projects.github.p61": "Construindo um ChatbotFit no Telegram com JavaScript e NodeJS",
    "projects.github.p62": "Construindo sexy APIs Usando Arquitetura Serverless",
    "projects.github.p63": "Tarefas em Background Utilizando Node.js e Redis",
    "projects.github.p64": "Requisitando Dados de uma API de Criptomoedas",
    "projects.github.p65": "Introdução Prática ao TypeScript",
    "projects.github.p66": "Conhecendo Spring Data JPA na prática com Java",
    "projects.github.p67": "Desafio Tech Pottencial: Payment API",
    "projects.github.p68": "Construindo um Sistema de Agendamento de Tarefas com Entity Framework",
    "projects.github.p69": "Criando um Sistema e Abstraindo um Celular com POO em C#",
    "projects.github.p70": "Construindo um Sistema de Hospedagem de um Hotel no C#",
    "projects.github.p71": "Construindo um Sistema para um Estacionamento com C#",
    "projects.github.p72": "O Papel dos Bancos de Dados SQL e NoSQL na Engenharia de Dados",
    "projects.github.p73": "Construa um Projeto Lógico de Banco de Dados do Zero",
    "projects.github.p74": "Construindo seu Primeiro Projeto Lógico de Banco de Dados",
    "projects.github.p75": "Construindo um Esquema Conceitual para Banco De dados",
    "projects.github.p76": "Refinando um Projeto Conceitual de Banco de Dados – E-COMMERCE",
    "projects.github.p77": ".Docker: Utilização Prática no Cenário de Microsserviços",
    "projects.github.p78": "Infraestrutura como Código - Script de Provisionamento de um Servidor Web (Apache)",
    "projects.github.p79": "Infraestrutura como Código: Script de Criação de Estrutura de Usuários, Diretórios e Permissões",
    "projects.github.p80": "Realizando Deploy na Nuvem de um Conjunto de API's Desenvolvida em Spring Boot",
    "projects.github.p81": "Integrando um Backend em Node.js com um Frontend em React para um E-commerce",
    "projects.github.p82": "Desenvolvendo um Menu Hamburguer e Morphing Menu com CSS Transitions",
    "projects.github.p83": "Construindo um App usando Sensor de Movimento com React Native",
    "projects.github.p84": "Aprenda a Criar um Sistema de Estacionamento Usando TypeScript",
    "projects.github.p85": "Como criar um front-end de um e-commerce utilizando Angular",
    "projects.github.p86": "Desenvolvendo uma Progressive Web Application com React para Mapear os Dados do COVID19 Pelo Mundo",
    "projects.github.p87": "Desenvolvimento de Testes Unitários para Validar uma API REST de Gerenciamento Estoques de Cerveja",
    "projects.github.p88": "Crie seu Gerenciador de Salas de Reuniões com Java e Angular",
    "projects.github.p89": "Construindo uma API Rest de Consulta de Cidades do Brasil do Zero até a Produção",
    "projects.github.p90": "Desenvolvendo um Sistema de Gerenciamento de Pessoas em API REST com Spring Boot",
    "projects.github.p91": "Criando seu Jogo no Estilo Space Shooter",
    "projects.github.p92": "Criando seu Próprio Jogo da Velha com HTML e Javascript",
    "projects.github.p93": "Desenvolvendo um Jogo da Memória",
    "projects.github.p94": "Construindo o seu Primeiro Jogo de Naves",
    "projects.github.p95": "Recriando o Famoso Jogo do Dinossauro sem Internet",
    "projects.github.p96": "Criando um Ecossistema Hadoop Totalmente Gerenciado com Google Cloud Dataproc",
    "projects.github.p97": "MySql - Como Modelar um Banco de Controle de Séries Assistidas",
    "projects.github.p98": "Descomplicando a Criação de Pacotes de Processamento de Imagens em Python",
    "projects.github.p99": "Construindo Encurtador de URL",
    "projects.github.p100": "Criando um Front-end Totalmente Componentizado na Prática com ReactJS",
    "projects.github.p101": "Criando seu Jogo de Memória Estilo Genius",
    "projects.github.p102": "Criando um App para Apresentar seu Portfólio do GitHub",
    "projects.github.p103": "Criando um App de Cartão de Visitas em Kotlin",
    "projects.github.p104": "Criando um App de Lembretes e Tarefas com Kotlin",
    "projects.github.p105": "Explorando Padrões de Projetos na Prática com Java",
    "projects.github.p106": "Abstraindo um Bootcamp Usando Orientação a Objetos em Java",
    "projects.github.p107": "Criando um Banco Digital com Java e Orientação a Objetos",
    "projects.github.p108": "Abstraindo um Jogo de RPG Usando Orientação a Objetos com C#",
    "projects.github.p109": "Recriando o Jogo da Cobrinha com JavaScript",
    "projects.github.p110": "Recriando a Interface do Netflix",
    "projects.github.p111": "Recriando a Página Inicial do Instagram",
    "projects.github.p112": "Criando seu Primeiro Repositório no GitHub Para Compartilhar Seu Progresso",
    "projects.github.p113": "Criando um APP Simples de Cadastro de Séries em .NET",
    "projects.github.p114": "Criando uma Aplicação de Transferências Bancárias com .NET",
    "projects.github.p115": "Criando seu CV Online com HTML e GitHub Pages",
    "projects.github.p116": "Criando Soluções Robusta em Dynamics 365 com a Extensão do SDK",
    "projects.github.p117": "Documentando e Testando sua API Rest com Kotlin",
    "projects.github.p118": "Contribuindo para um Projeto Open Source no GitHub",
    "projects.github.p119": "Simulando uma Conta Bancária Através do Terminal/Console",
    "projects.github.p120": "Criando um Pequeno Sistema para Validação de um Processo Seletivo",
    "projects.github.p121": "Modelando o iPhone com UML: Funções de Música, Ligações e Internet",
    "projects.github.p122": "Publicando sua API Rest na Nuvem Usando Spring Boot 3, Java 17 e Railway",
    "projects.github.p123": "Recriando a Interface da PlayStation Store com Angular",
    "projects.github.p124": "Explorando IA Generativa em um Pipeline de ETL com Python",
    "projects.github.p125": "Criando Um Relatório Gerencial de Vendas com Power BI",
    "projects.github.p126": "Criando um Dashboard corporativo com integração com MySQL e Azure",
    "projects.github.p127": "Personalizando o Banco de Dados com Índices e Procedures",
    "projects.github.p128": "Personalizando acessos e automatizando ações no MySQL",
    "projects.github.p129": "Criando Transações, Executando Backup e Recovery de Banco de Dados",
    "projects.github.p130": "Analisando dados de um Dashboard de Vendas no Power BI",
    "projects.github.p131": "Dashboard de Vendas com Power BI utilizando Star Schema",
    "projects.github.p132": "Modelando um Dashboard de E-commerce com Power BI Utilizando Fórmulas DAX",
    "projects.github.p133": "Criando um Dashboard Gerencial para Tomada de Decisões Com Power BI",
    "projects.github.p134": "Criando um Relatório Vendas e Lucros com Data Analytics com Power BI",
    "projects.github.p135": "Criando Relatórios Dinâmicos com o uso de Parâmetros no Power BI",
    "projects.github.p136": "Criando e Utilizando a Sua Carteira de Criptomoedas",
    "projects.github.p137": "Criando a Sua Primeira Criptomoeda da Rede Ethereum",
    "projects.github.p138": "Crie o seu NFT de Pokémon com Blockchain",
    "projects.github.p139": "Criando o Seu Primeiro Token do Zero nos Padrões Web3",
    "projects.github.p140": "Criando um NFT na Prática",
    "projects.github.p141": "Criando uma Organização Autônoma Descentralizada nos Padrões Web3",
    "projects.github.p142": "Recriando o Wikipedia com Layout Moderno",
    "projects.github.p143": "Clonando a Página do Youtube com CSS",
    "projects.github.p144": "Reproduzindo a Listagem do YouTube com Grid Layout no CSS",
    "projects.github.p145": "Construindo um Layout Responsivo Para o Site do Discord Com CSS",
    "projects.github.p146": "Clonando o Site da HBO Max com Animações em HTML e CSS",
    "projects.github.p147": "Publicando Seu Portfólio Profissional no GitHub Pages",
    "projects.github.p148": "Criando o Seu Blog Pessoal Com Next.js",
    "projects.github.p149": "Criando um RG pro Creeper do Minecraft com a Linguagem Lua",

    "footer.social": "Minhas Redes Sociais",
    "footer.powered": "Desenvolvido com w3.css"
  },

  "es-ES": {
    "meta.title": "Nivaldo Beirão - CV Online",
    "name": "Nivaldo José Tadeu dos Santos Beirão",
    "role": "Especialista en Gobernanza y Gestión de TI | GRC & Compliance | Procesos Administrativos | Soporte Técnico Estratégico | Especialista en Gestión del Moodle",
    "location": "Remoto / Brasil (GMT-3)",
    
    // Hard Skills
    "skills.Hard-title": "Hard Skills",
    "skills.IT_Management": "Gestión de TI",
    "skills.IT_Governance": "Gobernanza de TI",
    "skills.Project-Management": "Gestión de Proyectos",
    "skills.Strategic-Planning": "Planificación Estratégica",
    "skills.Moodle": "Moodle",
    "skills.Standardized_Work": "Trabajo Estándar",
    "skills.Process_Optimization": "Optimización de Procesos",
    "skills.Financial_Risk_Management": "Gestión de Riesgos Financieros",
    "skills.Compliance_Management": "Gestión de Conformidad",
    "skills.Administrative_Support": "Soporte Administrativo",
    "skills.Technical_Support": "Soporte Técnico",
    "skills.Microsoft_Excel": "Microsoft Excel",
    "skills.Calculation": "Cálculo",
    "skills.JavaScript": "JavaScript",
    "skills.HTML": "HTML",
    "skills.CSS": "CSS",
    "skills.Banking_Operations": "Operaciones Bancarias",
    "skills.Customer_Service": "Atención al Cliente",
    "skills.Internal_Process_Audit": "Auditoría de Procesos Internos",
    "skills.Inventory_and_Asset_Management": "Gestión de Stock y Activos",
    
    // Soft Skills
    "skills.Soft-title": "Soft Skills",
    "skills.Analytical_Thinking": "Pensamiento Analítico",
    "skills.Emotional_Intelligence": "Inteligencia Emocional",
    "skills.Teamwork": "Trabajo en Equipo",
    "skills.Organization": "Organización",
    "skills.Resilience": "Resiliencia",
    "skills.Critical_Thinking": "Pensamiento Crítico",
    "skills.Leadership": "Liderazgo",
    "skills.People_Management": "Gestión de Personas",
    
    "languages.title": "Idiomas",
    "languages.pt": "Portugués",
    "languages.en": "Inglés",
    "languages.es": "Español",
    
    "about.title": "Acerca de",
    "about.text": "Especialista en Gobernanza y Gestión de TI con sólida formación en Administración de Empresas y enfoque en Eficiencia Operativa y GRC (Gobernanza, Riesgo y Cumplimiento). Experiencia en el desarrollo de procesos auditables, cumplimiento normativo y gestión de activos digitales a gran escala mediante Inteligencia Artificial. Perfil analítico y resiliente, con un historial de excelencia técnica (Harvard CC50) y enfoque en la estabilidad del servicio y la mitigación de riesgos. Inteligencia Artificial: IA en la práctica, Ingeniería Prompt para la productividad administrativa y la automatización de procesos. Marcos de trabajo: Fundamentos de ITIL y Cuadro de Mando Integral (CMI).",
    
    "experience.title": "Experiencias",
    "experience.multimedia.title": "Editor Multimedia y Gerente de Ativos Digitales - Trabajo Freelance con Audacity",
    "experience.multimedia.date_text": "Abril 2023 -",
    "experience.multimedia.date_tag": "Presente",
    "experience.multimedia.p1": "Creación y edición de contenido multimedia digital enfocado en calidad, creatividad e innovación en IA.",
    "experience.multimedia.p2": "Texto: subtitulado, traducción y adaptación para diferentes audiencias.",
    "experience.multimedia.p3": "Imagen: diseño de portada, edición profesional y ajustes de píxeles.",
    "experience.multimedia.p4": "Audio: conversión, cortes y ajustes, efectos de sonido, reverb, normalización y ecualización.",
    "experience.multimedia.p5": "Video: edición dinámica, edición de escenas, ajustes de audio, subtítulos y traducciones asistidas por IA.",
    "experience.multimedia.p6": "Resultados: +8.000 archivos de audio editados y guardados en la nube; +550 videos publicados con subtítulos y traducciones en Portugués, Inglés y Español.",
    
    "experience.sports-trader.title": "Analista de Riesgo y Inteligencia de Mercado - Trabajo Freelance en Betfair",
    "experience.sports-trader.date_text": "Marzo 2021 -",
    "experience.sports-trader.date_tag": "Diciembre 2021",
    "experience.sports-trader.p1": "Área de enfoque: Análisis estadístico, GRC (Gobernanza, Riesgo y Cumplimiento) y gestión de activos en mercados altamente volátiles.",
    "experience.sports-trader.p2": "Desarrollo y ejecución de modelos predictivos basados en probabilidad y estadística aplicada, con control riguroso de riesgos operativos y cumplimiento de estrategias de mercado." ,
    "experience.sports-trader.p3": "Responsabilidades y Gobernanza (GRC): modelado de riesgo y cumplimiento, análisis de variables complejas para apoyar la toma de decisiones estratégicas en tiempo real, garantizando la integridad de los procesos y el cumplimiento de los modelos de riesgo establecidos.",
    "experience.sports-trader.p4": "Gestión de Riesgos (Bankroll Management): gestión de capital enfocada en la preservación de activos y mitigación de pérdidas, utilizando herramientas de auditoría y \"logbooks\" para garantizar la gobernanza sobre las inversiones.",
    "experience.sports-trader.p5": "Análisis Cuantitativo y Precificación: estudio avanzado de la precificación de activos (ODDs), evaluando volatilidad y puntos de resistencia, asegurando que las operaciones estén dentro de métricas de riesgo aceptables.",
    "experience.sports-trader.p6": "Disciplina Operacional y Auditoría: mantenimiento de alto rigor analítico bajo presión, garantizando que el 100% de las estrategias siguieran el plan de gobernanza operacional preestablecido, sin desviaciones de conducta o ejecución.",
    "experience.sports-trader.p7": "Resultados y Competencias: inteligencia de datos, transformación de datos brutos en decisiones de inversión, utilizando calculadoras estadísticas y análisis de tendencias de mercado; resiliencia y control de riesgos, dominio de técnicas de gestión de bankroll y control psicológico, fundamentales para la sostenibilidad de las operaciones en ambientes altamente inciertos.",
    "experience.sports-trader.p8": "Resultados y Competencias:",
    "experience.sports-trader.p9": "Inteligencia de Datos: Transformación de datos brutos en decisiones de inversión, utilizando calculadoras estadísticas y análisis de tendencias de mercado.",
    "experience.sports-trader.p10": "Resiliencia y Control de Riesgos: Dominio de técnicas de gestión de bankroll y control psicológico, fundamentales para la sostenibilidad de las operaciones en ambientes altamente inciertos.",
    
    "experience.administrative-assistant.title": "Asistente Administrativo - Centro Universitario Vale Do Ribeira (Univr)",
    "experience.administrative-assistant.date_text": "Julio 2016 -",
    "experience.administrative-assistant.date_tag": "Septiembre 2019",
    "experience.administrative-assistant.p1": "Área de Actuación: Gestión de Datos Educacionales, GRC (Gobernanza, Riesgo y Cumplimiento) y Soporte Tecnológico para Ambientes Virtuales.",
    "experience.administrative-assistant.p2": "Papel estratégico en el desarrollo de soluciones tecnológicas aplicadas a la educación, con enfoque en la gobernanza de datos académicos y conformidad con estándares regulatorios federales (MEC).",
    "experience.administrative-assistant.p3": "Responsabilidades y Gobernanza (GRC):",
    "experience.administrative-assistant.p4": "Gobernanza de Datos Regulatoria (MEC/ENADE): Soporte directo al Investigador Institucional en la recopilación y procesamiento de datos para el Censo de la Educación Superior. Garantía de la integridad, confiabilidad y conformidad de los datos reportados al MEC, mitigando riesgos de irregularidades institucionales.",
    "experience.administrative-assistant.p5": "Gestión de Procesos y Auditoría: Preparación, control y gestión de documentos y reportes críticos en Excel, garantizando conformidad con plazos regulatorios y organización del flujo académico.",
    "experience.administrative-assistant.p6": "Administración de Ambiente Virtual de Aprendizaje (AVA): Gestión de la plataforma Moodle, definiendo estándares de seguridad y usabilidad para más de 2.500 usuarios.",
    "experience.administrative-assistant.p7": "Gestión de Flujo y Calendario: Organización de cronogramas académicos complejos (Urânia) y calendarios de actividades vía Google Sheets, optimizando la asignación de recursos institucionales.",
    "experience.administrative-assistant.p8": "Resultados y Competencias Técnicas:",
    "experience.administrative-assistant.p9": "Estandarización y Escalabilidad: Gestión del LMS Moodle con la creación de templates para 27 cursos (Presencial y EAD), garantizando consistencia visual y operativa para la institución.",
    "experience.administrative-assistant.p10": "Soporte Estratégico: Provisión de soporte técnico especializado a coordinadores y cuerpo docente, asegurando la continuidad operativa de las clases síncronas y asíncronas.",
    "experience.administrative-assistant.p11": "Transición Institucional: Participación activa en el proceso de transición tecnológica de Facultad a Centro Universitario, garantizando la conformidad de los sistemas de datos durante la expansión hacia la Educación a Distancia.",
    
    "experience.intern-registro.title": "Pasante de Administración - Unidad Regional de Educación de Registro",
    "experience.intern-registro.date_text": "Julio 2014 -",
    "experience.intern-registro.date_tag": "Julio 2016",
    "experience.intern-registro.p1": "Área de especialización: Soporte estratégico de TI, GRC (Control y Cumplimiento de Activos) y Gestión de Proyectos Educativos.",
    "experience.intern-registro.p2": "Experiencia laboral en el NIET (Centro de Información y Tecnología Educativa), con enfoque en la infraestructura de TI y la gestión de datos operativos para la red educativa estatal.",
    "experience.intern-registro.p3": "Responsabilidades y Gobernanza (GRC):",
    "experience.intern-registro.p4": "Gestión de inventario y datos (Excel intermedio): Creación y mantenimiento de hojas de cálculo de control para la gestión de activos tecnológicos en 40 centros educativos. Uso de fórmulas de búsqueda y tablas dinámicas para el monitoreo del hardware y el estado de mantenimiento.",
    "experience.intern-registro.p5": "Cumplimiento y Gobernanza de TI: Garantizar la estandarización y seguridad de las redes locales y los dispositivos móviles, asegurando que el uso de herramientas digitales se ajustara a las directrices del Ministerio de Educación.",
    "experience.intern-registro.p6": "Gestión de incidentes (Mesa de Ayuda): Soporte de nivel 1 (presencial/remoto) a través de TeamViewer y WhatsApp Business, con enfoque en la resolución rápida y el registro de incidentes para auditorías de soporte.",
    "experience.intern-registro.p7": "Planificación de proyectos de inclusión: Asistencia en la ejecución de cronogramas y el seguimiento de objetivos para programas de capacitación tecnológica a gran escala.",
    "experience.intern-registro.p8": "Resultados y competencias:",
    "experience.intern-registro.p9": "Capacitación multiplicadora: Capacitación y gestión directa de más de 200 monitores durante 2 años, difundiendo las mejores prácticas para el uso y la seguridad de la información.",
    "experience.intern-registro.p10": "Escalabilidad del servicio: Soporte técnico activo a 40 centros educativos, garantizando la continuidad de las operaciones pedagógicas y administrativas en la región.",

    "experience.intern-miracatu.title": "Pasante de Administración - Unidad Regional de Educación de Miracatu",
    "experience.intern-miracatu.date_text": "Agosto 2011 -",
    "experience.intern-miracatu.date_tag": "Agosto 2013",
    "experience.intern-miracatu.p1": "Área de especialización: Soporte estratégico de TI, GRC (Control y Cumplimiento de Activos) y Gestión de Proyectos Educativos.",
    "experience.intern-miracatu.p2": "Experiencia laboral en el NIET (Centro de Información y Tecnología Educativa), con enfoque en la infraestructura de TI y la gestión de datos operativos para la red educativa estatal.",
    "experience.intern-miracatu.p3": "Responsabilidades y Gobernanza (GRC):",
    "experience.intern-miracatu.p4": "Gestión de inventario y datos (Excel intermedio): Creación y mantenimiento de hojas de cálculo de control para la gestión de activos tecnológicos en 28 centros educativos. Uso de fórmulas de búsqueda y tablas dinámicas para el monitoreo del hardware y el estado de mantenimiento.",
    "experience.intern-miracatu.p5": "Cumplimiento y Gobernanza de TI: Garantizar la estandarización y seguridad de las redes locales y los dispositivos móviles, asegurando que el uso de herramientas digitales se ajustara a las directrices del Ministerio de Educación.",
    "experience.intern-miracatu.p6": "Gestión de incidentes (Mesa de Ayuda): Soporte de nivel 1 (presencial/remoto) a través de TeamViewer y WhatsApp Business, con enfoque en la resolución rápida y el registro de incidentes para auditorías de soporte.",
    "experience.intern-miracatu.p7": "Planificación de proyectos de inclusión: Asistencia en la ejecución de cronogramas y el seguimiento de objetivos para programas de capacitación tecnológica a gran escala.",
    "experience.intern-miracatu.p8": "Resultados y competencias:",
    "experience.intern-miracatu.p9": "Capacitación multiplicadora: Capacitación y gestión directa de más de 150 monitores durante 2 años, difundiendo las mejores prácticas para el uso y la seguridad de la información.",
    "experience.intern-miracatu.p10": "Escalabilidad del servicio: Soporte técnico activo a 28 centros educativos, garantizando la continuidad de las operaciones pedagógicas y administrativas en la región.",
    
    "experience.cashier-bank.title": "Cajero - Banco Bradesco",
    "experience.cashier-bank.date_text": "Abril 2009 -",
    "experience.cashier-bank.date_tag": "Marzo 2011",
    "experience.cashier-bank.p1": "Área de enfoque: Gestión de operaciones financieras, GRC (Gobierno, Riesgo y Cumplimiento) y Cumplimiento bancario.",
    "experience.cashier-bank.p2": "Desempeño estratégico en atención al cliente y gestión de efectivo, con un enfoque total en la precisión, la mitigación de riesgos operativos y el cumplimiento de las normas regulatorias.",
    "experience.cashier-bank.p3": "Responsabilidades y Gobernanza (GRC):",
    "experience.cashier-bank.p4": "Control de flujo de efectivo y gestión de riesgos: Responsable de la apertura, cierre y conciliación diaria de fondos, garantizando la precisión del 100% en los registros y actuando en la prevención de pérdidas y fraudes.",
    "experience.cashier-bank.p5": "Cumplimiento y procesamiento de activos: Gestión de pagos, impuestos y acuerdos, garantizando la integridad de las transacciones y el cumplimiento de las directrices del Banco Central y los protocolos internos.",
    "experience.cashier-bank.p6": "Soporte crítico y auditoría de procesos: Soporte a beneficiarios y proveedores del INSS, realizando una verificación rigurosa de documentos para garantizar la seguridad institucional.",
    "experience.cashier-bank.p7": "Gobernanza de datos y documentación: Control de la correspondencia y los documentos críticos, garantizando la trazabilidad completa y la organización del flujo administrativo de acuerdo con los estándares de auditoría.",
    "experience.cashier-bank.p8": "Resultados y Competencias:",
    "experience.cashier-bank.p9": "Gestión de crisis y transición: Participación activa en la migración de sistemas operativos, asegurando que la transición tecnológica respetara los pilares de gobernanza y no afectara el cumplimiento de los servicios.",
    "experience.cashier-bank.p10": "Multiplicador del cumplimiento: Responsable de la formación e integración de nuevos empleados, difundiendo la cultura de seguridad, ética y las normas GRC de la institución.",
    "experience.cashier-bank.p11": "Excelencia operativa: Reconocimiento por la resolución de conflictos en entornos de alta presión y la fidelización de clientes mediante procesos seguros y transparentes.",
    
    "experience.general-services.title": "Asistente de Operaciones y Ventas (Comercio Minorista) - Supermercados Tio Beba",
    "experience.general-services.date_text": "Enero 2009 -",
    "experience.general-services.date_tag": "Marzo 2011",
    "experience.general-services.p1": "Gestión de Procesos Operativos, Inventario y Flujo de Caja",
    "experience.general-services.p2": "Rol multifuncional enfocado en la organización, el control de activos y la excelencia en el servicio al cliente, garantizando el cumplimiento de las normas de la empresa con rigor técnico y ético.",
    "experience.general-services.p3": "Responsabilidades y Gobernanza:",
    "experience.general-services.p4": "Gestión de Caja: Responsable de las operaciones de caja, asegurando la precisión del 100% en los cierres y la verificación de facturas y correspondencia.",
    "experience.general-services.p5": "Logística e Inventario: Organización estratégica del inventario y del área de ventas, optimizando el tiempo de reposición y asegurando la precisión en la verificación de envíos.",
    "experience.general-services.p6": "Versatilidad Administrativa: Apoyo directo en las rutinas de compras, precios y control de archivos, manteniendo el orden de la documentación institucional.",
    "experience.general-services.p7": "Servicio y Soporte al Cliente: Integración entre las áreas administrativa y comercial, enfocada en la resolución de problemas de los clientes y en brindar apoyo logístico (entregas).",
    "experience.general-services.p8": "Resultados y Competencias:",
    "experience.general-services.p9": "Eficiencia Operativa: Garantía del cumplimiento total en los procesos internos de auditoría de caja e inventario.",
    "experience.general-services.p10": "Agilidad y resiliencia: Capacidad para adaptarse a diferentes sectores (comercio, finanzas y logística), manteniendo un alto nivel de rendimiento bajo presión.",
    
    "education.title": "Educación",
    "education.dio.title": "Digital Innovation One (DIO)",
    "education.dio.date": "Octubre 2021 - Presente",
    "education.dio.text": "La mayor plataforma de educación abierta en TI de América Latina, con más de 1 millón de usuarios. DIO se asocia con empresas innovadoras, proporcionando experiencias de aprendizaje inmersivas centradas en la empleabilidad. Principales certificaciones listadas a continuación.",
    "education.univr.mba": "CENTRO UNIVERSITARIO VALE DO RIBEIRA (UNIVR) - MBA",
    "education.univr.mba.date": "2017 - 2018",
    "education.univr.mba.title": "MBA en Gestión y Gobernanza de Tecnología de la Información",
    "education.univr.mba.text": "Enfoque en marcos de gobernanza, cumplimiento tecnológico y gestión estratégica de activos de TI. Desarrollo de habilidades en auditoría de sistemas, seguridad de la información y alineación entre tecnología y objetivos de negocio.",
    "education.univr.bachelor": "CENTRO UNIVERSITARIO VALE DO RIBEIRA (UNIVR) - Licenciatura",
    "education.univr.bachelor.date": "2010 - 2017",
    "education.univr.bachelor.title": "Licenciatura en Administración de Empresas",
    "education.univr.bachelor.text": "Amplia experiencia en gestión organizacional, procesos administrativos, derecho aplicado y finanzas. Enfoque en el desarrollo de una visión sistémica y análisis de procesos para la eficiencia operativa.",

    "projects.title": "Proyectos",
    "projects.github": "GitHub",
    "projects.github.p1": "Creando una aplicación tipo Canvas con Power Platform",
    "projects.github.p2": "Agregando Seguridad a APIs en AWS con Amazon Cognito",
    "projects.github.p3": "Explorando Rest Assured para la Automatización de Pruebas de API",
    "projects.github.p4": "Profesional de QA: Pruebas Funcionales Manuales",
    "projects.github.p5": "Implementando Pantalla de Login con Validación Usando TypeScript",
    "projects.github.p6": "Desarrollando la Pantalla de Registro de la Plataforma DIO con React",
    "projects.github.p7": "Creando una Wiki de Repositorio de GitHub con React",
    "projects.github.p8": "Identificar Sus Habilidades que Pueden Monetizarse",
    "projects.github.p9": "IA Entrevistador: Su Simulador Inteligente de Entrevistas",
    "projects.github.p10": "IA Mentor de Carrera: Descubra Su Futuro en Tech",
    "projects.github.p11": "Creando una Aplicación de Organización de Finanzas Personales con Vibe Coding",
    "projects.github.p12": "Creando una Calculadora con React",
    "projects.github.p13": "Abstrayendo Formaciones de DIO Usando Orientación a Objetos con Kotlin",
    "projects.github.p14": "Creando un Clon de BuzzFeed con Angular",
    "projects.github.p15": "Creando un Blog con Angular",
    "projects.github.p16": "Construyendo una Pokédex con JavaScript",
    "projects.github.p17": "Creando tu Primera Página de Destino con HTML y CSS",
    "projects.github.p18": "Creando tu Primer Sitio Web Completo con HTML",
    "projects.github.p19": "Creando una Página Web Usando Etiquetas Aprendidas",
    "projects.github.p20": "Creando un Pipeline de CI/CD con Cloud Build y Terraform",
    "projects.github.p21": "Utilizando Cloud Shell",
    "projects.github.p22": "Personalizando el Panel y Cambiando las Preferencias de Idioma",
    "projects.github.p23": "Exportación de Facturación en Google Cloud Platform",
    "projects.github.p24": "Definición de Presupuesto de Facturación en Google Cloud Platform",
    "projects.github.p25": "Diseñando Su Organización de Carpetas y Proyectos y Grupos de Acceso en Google Cloud Platform",
    "projects.github.p26": "Creando un Pipeline de Implementación con GitLab y Kubernetes",
    "projects.github.p27": "Creando una Implementación de Aplicación",
    "projects.github.p28": "Definición de un Clúster Swarm Local con Vagrant",
    "projects.github.p29": "Creando un Contenedor para una Aplicación WEB",
    "projects.github.p30": "Explorando Datos Demográficos con Servicios de Big Data en AWS",
    "projects.github.p31": "Entrenamiento de Redes Neuronales con Transfer Learning",
    "projects.github.p32": "Mejores Prácticas con DynamoDB",
    "projects.github.p33": "Creando Modelos con Python y Machine Learning para Predecir la Evolución del COVID-19 en Brasil",
    "projects.github.p34": "Aplicación Nativa Sobre Fútbol Femenino con Android Jetpack y Java",
    "projects.github.p35": "Creando el Front-end con ReactJS",
    "projects.github.p36": "Aplicación de Reserva DIO",
    "projects.github.p37": "Creando la Interfaz de iFood con React Native",
    "projects.github.p38": "Infraestructura como Código con Serverless Framework en AWS",
    "projects.github.p39": "Creando un Administrador de Naves de Star Wars con SQL Server + .NET",
    "projects.github.p40": "Creando una Aplicación para Conversión y Cambio de Divisas",
    "projects.github.p41": "Desarrollando su Blog con Tecnologías de Java y Angular",
    "projects.github.p42": "Creando una Aplicación de Noticias ReactJS Usando PWA",
    "projects.github.p43": "Creando un Sitio Web para Encontrar Restaurantes Usando Google Maps que Consulta la API de Google",
    "projects.github.p44": "Creando su Ecosistema de Big Data en la Nube",
    "projects.github.p45": "Análisis de Datos con Python y Pandas",
    "projects.github.p46": "Creando un Catálogo de Juegos Usando Mejores Prácticas de Arquitectura con .NET",
    "projects.github.p47": "Construyendo un Proyecto con Arquitectura Basada en Microservicios Usando Spring Cloud",
    "projects.github.p48": "Construyendo un Sistema de Control de Tiempo y Acceso con Spring Boot",
    "projects.github.p49": "Creando un Sistema de Clasificados con Ruby on Rails",
    "projects.github.p50": "MindApp - Desarrollando Cloud Tags con Ruby",
    "projects.github.p51": "Cree un Administrador de Esferas de Dragon Ball Z Usando ReactJS, Jest, React Testing Library y Cypress",
    "projects.github.p52": "Desarrollando SPA con Angular",
    "projects.github.p53": "Creando un Sistema de Presupuesto, Usando CQRS, Quarkus, Kafka e Implementación en EKS",
    "projects.github.p54": "Ejecutando su Aplicación Java en Kubernetes. ¡De la Implementación al Depuración sin Miedo!",
    "projects.github.p55": "Creando una Solución de Comercio Electrónico con Microservicios en Java",
    "projects.github.p56": "Creando su Administrador de Superhéroes de Marvel y DC en una API Reactiva con Spring Boot",
    "projects.github.p57": "Usando Cypress E2E para Probar un Blog en Angular",
    "projects.github.p58": "Creando Proyecto para Consultar Pronóstico del Tiempo vía API",
    "projects.github.p59": "Implementando su Stack de Pruebas Unitarias e Integradas en un Proyecto .NET Crowdfunding",
    "projects.github.p60": "Construyendo un Proyecto de API .NET Integrado con MongoDB",
    "projects.github.p61": "Construyendo un ChatbotFit en Telegram con JavaScript y NodeJS",
    "projects.github.p62": "Construyendo APIs Atractivas Usando Arquitectura Sin Servidor",
    "projects.github.p63": "Tareas en Segundo Plano Utilizando Node.js y Redis",
    "projects.github.p64": "Solicitando Datos de una API de Criptomonedas",
    "projects.github.p65": "Introducción Práctica a TypeScript",
    "projects.github.p66": "Aprendiendo Spring Data JPA en la Práctica con Java",
    "projects.github.p67": "Desafío Técnico Potencial: API de Pago",
    "projects.github.p68": "Construyendo un Sistema de Programación de Tareas con Entity Framework",
    "projects.github.p69": "Creando un Sistema y Abstrayendo un Teléfono Inteligente con OOP en C#",
    "projects.github.p70": "Construyendo un Sistema de Hospedaje de Hotel en C#",
    "projects.github.p71": "Construyendo un Sistema de Estacionamiento con C#",
    "projects.github.p72": "El Papel de las Bases de Datos SQL y NoSQL en la Ingeniería de Datos",
    "projects.github.p73": "Construya un Proyecto de Base de Datos Lógica desde Cero",
    "projects.github.p74": "Construyendo su Primer Proyecto de Base de Datos Lógica",
    "projects.github.p75": "Construyendo un esquema de Base de Datos Conceptual",
    "projects.github.p76": "Refinando un Diseño de Base de Datos Conceptual – COMERCIO ELECTRÓNICO",
    "projects.github.p77": ".Docker: Uso Práctico en el Escenario de Microservicios",
    "projects.github.p78": "Infraestructura como Código - Script de Aprovisionamiento de Servidor Web (Apache)",
    "projects.github.p79": "Infraestructura como Código: Script para Crear Estructura de Usuario, Directorio y Permisos",
    "projects.github.p80": "Realizando Implementación en la Nube de un Conjunto de API Desarrolladas en Spring Boot",
    "projects.github.p81": "Integrando un Backend de Node.js con un Frontend de React para un Comercio Electrónico",
    "projects.github.p82": "Desarrollando un Menú Hamburguesa y Menú Morfing con Transiciones CSS",
    "projects.github.p83": "Construyendo una Aplicación Usando Sensor de Movimiento con React Native",
    "projects.github.p84": "Aprenda a Crear un Sistema de Estacionamiento Usando TypeScript",
    "projects.github.p85": "Cómo Crear un Front-end para un Comercio Electrónico Usando Angular",
    "projects.github.p86": "Desarrollando una Aplicación Web Progresiva con React para Mapear Datos de COVID-19 en Todo el Mundo",
    "projects.github.p87": "Desarrollo de Pruebas Unitarias para Validar una API REST para la Gestión del Inventario de Cerveza",
    "projects.github.p88": "Cree su Administrador de Salas de Reuniones con Java y Angular",
    "projects.github.p89": "Construyendo una API REST para Consultar Ciudades Brasileñas de Cero a Producción",
    "projects.github.p90": "Desarrollando un Sistema de Gestión de Personas en API REST con Spring Boot",
    "projects.github.p91": "Creando tu Juego en Estilo Space Shooter",
    "projects.github.p92": "Creando tu Propio Juego de Tic-Tac-Toe con HTML y Javascript",
    "projects.github.p93": "Desarrollando un Juego de Memoria",
    "projects.github.p94": "Construyendo tu Primer Juego de Naves",
    "projects.github.p95": "Recreando el Famoso Juego del Dinosaurio sin Internet",
    "projects.github.p96": "Creando un Ecosistema Hadoop Completamente Administrado con Google Cloud Dataproc",
    "projects.github.p97": "MySql - Cómo Modelar una Base de Datos de Control de Series Observadas",
    "projects.github.p98": "Simplificando la Creación de Paquetes de Procesamiento de Imágenes en Python",
    "projects.github.p99": "Construyendo un Acortador de URL",
    "projects.github.p100": "Creando un Front-end Totalmente Componentizado en la Práctica con ReactJS",
    "projects.github.p101": "Creando tu Juego de Memoria Estilo Genius",
    "projects.github.p102": "Creando una Aplicación para Mostrar tu Portafolio de GitHub",
    "projects.github.p103": "Crear un Aplicación de Tarjeta de Visita en Kotlin",
    "projects.github.p104": "Creando una Aplicación de Recordatorios y Tareas con Kotlin",
    "projects.github.p105": "Explorando Patrones de Diseño en la Práctica con Java",
    "projects.github.p106": "Abstrayendo un Bootcamp Usando Orientación a Objetos en Java",
    "projects.github.p107": "Creando un Banco Digital con Java y Orientación a Objetos",
    "projects.github.p108": "Abstrayendo un Juego RPG Usando Orientación a Objetos con C#",
    "projects.github.p109": "Recreando el Juego de la Serpiente con JavaScript",
    "projects.github.p110": "Recreando la Interfaz de Netflix",
    "projects.github.p111": "Recreando la Página de Inicio de Instagram",
    "projects.github.p112": "Creando tu Primer Repositorio de GitHub para Compartir tu Progreso",
    "projects.github.p113": "Creando una Aplicación Simple de Registro de Series en .NET",
    "projects.github.p114": "Creando una Aplicación de Transferencia Bancaria con .NET",
    "projects.github.p115": "Creando tu CV Online con HTML y GitHub Pages",
    "projects.github.p116": "Creando Soluciones Robusta en Dynamics 365 con la Extensión del SDK",
    "projects.github.p117": "Documentando y Probando tu API Rest con Kotlin",
    "projects.github.p118": "Contribuyendo a un Proyecto Open Source en GitHub",
    "projects.github.p119": "Simulando una Cuenta Bancaria a Través del Terminal/Consola",
    "projects.github.p120": "Creando un Pequeño Sistema para Validar un Proceso de Selección",
    "projects.github.p121": "Modelando el iPhone con UML: Funciones de Música, Llamadas e Internet",
    "projects.github.p122": "Publicando tu API Rest en la Nube Usando Spring Boot 3, Java 17 y Railway",
    "projects.github.p123": "Recreando la Interfaz de la PlayStation Store con Angular",
    "projects.github.p124": "Explorando IA Generativa en un Pipeline de ETL con Python",
    "projects.github.p125": "Creando Un Reporte Gerencial de Ventas con Power BI",
    "projects.github.p126": "Creando un Dashboard corporativo con integración con MySQL y Azure",
    "projects.github.p127": "Personalizando la Base de Datos con Índices y Procedures",
    "projects.github.p128": "Personalización del acceso y automatización de acciones en MySQL",
    "projects.github.p129": "Creación de transacciones, realización de copias de seguridad y recuperación de bases de datos",
    "projects.github.p130": "Analisando datos de un Dashboard de Vendas no Power BI",
    "projects.github.p131": "Panel de ventas con Power BI usando el esquema de estrella",
    "projects.github.p132": "Modelado de un panel de control de comercio electrónico con Power BI mediante fórmulas DAX",
    "projects.github.p133": "Creación de un panel de control de gestión para la toma de decisiones con Power BI",
    "projects.github.p134": "Creación de un informe de ventas y beneficios con análisis de datos mediante Power BI",
    "projects.github.p135": "Creación de informes dinámicos mediante parámetros en Power BI",
    "projects.github.p136": "Creación y uso de su billetera de criptomonedas",
    "projects.github.p137": "Cómo crear tu primera criptomoneda en la red Ethereum",
    "projects.github.p138": "Crea tu propio NFT de Pokémon con Blockchain",
    "projects.github.p139": "Creación de tu primer token desde cero utilizando los estándares Web3",
    "projects.github.p140": "Creación de un NFT en la práctica",
    "projects.github.p141": "Creación de una organización autónoma descentralizada utilizando los estándares Web3",
    "projects.github.p142": "Recreando Wikipedia con un diseño moderno",
    "projects.github.p143": "Clonar una página de YouTube con CSS",
    "projects.github.p144": "Reproducción de un listado de YouTube con diseño de cuadrícula en CSS",
    "projects.github.p145": "Creación de un diseño adaptable para el sitio web de Discord usando CSS",
    "projects.github.p146": "Clonando el sitio web de HBO Max con animaciones HTML y CSS",
    "projects.github.p147": "Publica tu portafolio profesional en GitHub Pages",
    "projects.github.p148": "Creación de tu blog personal con Next.js",
    "projects.github.p149": "Creación de una tarjeta de identificación para el Creeper de Minecraft usando Lua",
    
    "footer.social": "Mis Redes Sociales",
    "footer.powered": "Desarrollado con w3.css"
  }
};

/**
 * Apply translations to all elements that have a data-i18n attribute.
 * @param  {string} locale - locale key, e.g. 'en-US'
 */
function applyTranslations(locale) {
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    const text = translations[locale] && translations[locale][key];
    if (text !== undefined) {
      if (el.tagName.toLowerCase() === 'input' || el.tagName.toLowerCase() === 'textarea') {
        el.value = text;
      } else {
        el.textContent = text;
      }
    }
  });

  if (translations[locale] && translations[locale]['meta.title']) {
    document.title = translations[locale]['meta.title'];
  }
}

/* Language selector logic */
const languageSelect = document.getElementById('language-select');

const savedLang = localStorage.getItem('cv_lang') || 'en-US';
languageSelect.value = savedLang;
applyTranslations(savedLang);

languageSelect.addEventListener('change', (e) => {
  const newLang = e.target.value;
  applyTranslations(newLang);
  localStorage.setItem('cv_lang', newLang);
});
